-- ============================================================
-- V1: Add audit + tenant columns to GL tables
-- Required by AuditableEntity (CREATED_AT, CREATED_BY,
-- UPDATED_AT, UPDATED_BY) and TenantScoped (TENANT_ID)
-- ============================================================

-- ── ACCOUNTS_CHART ──────────────────────────────────────────

-- Audit columns
ALTER TABLE ACCOUNTS_CHART ADD (
    CREATED_AT   TIMESTAMP        DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY   VARCHAR2(100)    DEFAULT 'SYSTEM'     NOT NULL,
    UPDATED_AT   TIMESTAMP        NULL,
    UPDATED_BY   VARCHAR2(100)    NULL
);

-- Tenant column
ALTER TABLE ACCOUNTS_CHART ADD (
    TENANT_ID    VARCHAR2(64)     DEFAULT 'default'    NOT NULL
);

-- Indexes
CREATE INDEX IDX_ACCOUNTS_CHART_TENANT   ON ACCOUNTS_CHART (TENANT_ID);
CREATE INDEX IDX_ACCOUNTS_CHART_ACTIVE   ON ACCOUNTS_CHART (ACTIVE);
CREATE INDEX IDX_ACCOUNTS_CHART_ORG_FK   ON ACCOUNTS_CHART (ORGANIZATION_FK);
CREATE INDEX IDX_ACCOUNTS_CHART_PARENT_FK ON ACCOUNTS_CHART (ACCOUNT_CHART_FK);
CREATE INDEX IDX_ACCOUNTS_CHART_TYPE     ON ACCOUNTS_CHART (ACCOUNT_TYPE);

-- Unique constraint (tenant-aware)
ALTER TABLE ACCOUNTS_CHART ADD CONSTRAINT UK_ACCOUNTS_CHART_NO_ORG
    UNIQUE (ACCOUNT_CHART_NO, ORGANIZATION_FK, TENANT_ID);

-- Sequence (if not exists)
DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM user_sequences WHERE sequence_name = 'ACCOUNTS_CHART_SEQ';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE ACCOUNTS_CHART_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
    END IF;
END;
/

-- ── ACC_RULE_HDR ────────────────────────────────────────────

ALTER TABLE ACC_RULE_HDR ADD (
    CREATED_AT   TIMESTAMP        DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY   VARCHAR2(100)    DEFAULT 'SYSTEM'     NOT NULL,
    UPDATED_AT   TIMESTAMP        NULL,
    UPDATED_BY   VARCHAR2(100)    NULL
);

ALTER TABLE ACC_RULE_HDR ADD (
    TENANT_ID    VARCHAR2(64)     DEFAULT 'default'    NOT NULL
);

CREATE INDEX IDX_ACC_RULE_HDR_TENANT     ON ACC_RULE_HDR (TENANT_ID);
CREATE INDEX IDX_ACC_RULE_HDR_ACTIVE     ON ACC_RULE_HDR (IS_ACTIVE);
CREATE INDEX IDX_ACC_RULE_HDR_COMPANY_FK ON ACC_RULE_HDR (COMPANY_ID_FK);
CREATE INDEX IDX_ACC_RULE_HDR_MODULE     ON ACC_RULE_HDR (SOURCE_MODULE);

ALTER TABLE ACC_RULE_HDR ADD CONSTRAINT ACC_RULE_HDR_UK
    UNIQUE (COMPANY_ID_FK, SOURCE_MODULE, SOURCE_DOC_TYPE, TENANT_ID);

DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM user_sequences WHERE sequence_name = 'ACC_RULE_HDR_SEQ';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE ACC_RULE_HDR_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
    END IF;
END;
/

-- ── ACC_RULE_LINE ───────────────────────────────────────────

ALTER TABLE ACC_RULE_LINE ADD (
    CREATED_AT   TIMESTAMP        DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY   VARCHAR2(100)    DEFAULT 'SYSTEM'     NOT NULL,
    UPDATED_AT   TIMESTAMP        NULL,
    UPDATED_BY   VARCHAR2(100)    NULL
);

ALTER TABLE ACC_RULE_LINE ADD (
    TENANT_ID    VARCHAR2(64)     DEFAULT 'default'    NOT NULL
);

CREATE INDEX IDX_ACC_RULE_LINE_HDR_FK     ON ACC_RULE_LINE (RULE_ID_FK);
CREATE INDEX IDX_ACC_RULE_LINE_ACCOUNT_FK ON ACC_RULE_LINE (ACCOUNT_ID_FK);
CREATE INDEX IDX_ACC_RULE_LINE_TENANT     ON ACC_RULE_LINE (TENANT_ID);

DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM user_sequences WHERE sequence_name = 'ACC_RULE_LINE_SEQ';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE ACC_RULE_LINE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
    END IF;
END;
/