package com.example.erp.finance.gl.mapper;

import com.example.erp.finance.gl.dto.*;
import com.example.erp.finance.gl.entity.AccountsChart;
import org.hibernate.Hibernate;
import org.springframework.stereotype.Component;

import java.util.*;
import java.util.stream.Collectors;

@Component
public class AccountsChartMapper {

    /**
     * Maps create request to entity.
     * Note: accountChartNo is NOT set here — it is auto-generated by AccountChartNumberGenerator.
     */
    public AccountsChart toEntity(AccountsChartCreateRequest request) {
        return AccountsChart.builder()
                .accountChartName(request.getAccountChartName())
                .accountType(request.getAccountType())
                .organizationFk(request.getOrganizationFk())
                .organizationSubFk(request.getOrganizationSubFk())
                .isActive(request.getIsActive() != null ? request.getIsActive() : Boolean.TRUE)
                .build();
    }

    /**
     * Updates entity from update request.
     * Note: accountChartNo is immutable (auto-generated) and is NOT updated here.
     */
    public void updateEntity(AccountsChart entity, AccountsChartUpdateRequest request) {
        entity.setAccountChartName(request.getAccountChartName());
        entity.setAccountType(request.getAccountType());
        // organizationFk is immutable (R-008) — validated in service, NOT updated here
        entity.setOrganizationSubFk(request.getOrganizationSubFk());
        if (request.getIsActive() != null) {
            entity.setIsActive(request.getIsActive());
        }
    }

    public AccountsChartResponse toResponse(AccountsChart entity) {
        return AccountsChartResponse.builder()
                .accountChartPk(entity.getAccountChartPk())
                .accountChartNo(entity.getAccountChartNo())
                .accountChartName(entity.getAccountChartName())
                .accountType(entity.getAccountType())
                .accountChartFk(entity.getParent() != null ? entity.getParent().getAccountChartPk() : null)
                .parentAccountName(resolveParentName(entity))
                .parentAccountNo(entity.getParent() != null ? entity.getParent().getAccountChartNo() : null)
                .level(computeLevel(entity))
                .isActive(Boolean.TRUE.equals(entity.getIsActive()))
                .organizationFk(entity.getOrganizationFk())
                .organizationSubFk(entity.getOrganizationSubFk())
                .createdAt(entity.getCreatedAt())
                .createdBy(entity.getCreatedBy())
                .updatedAt(entity.getUpdatedAt())
                .updatedBy(entity.getUpdatedBy())
                .build();
    }

    /**
     * Recursively maps an entity and its children to a tree node for UI rendering.
     */
    public AccountsChartTreeNode toTreeNode(AccountsChart entity, int level) {
        List<AccountsChartTreeNode> childNodes = Collections.emptyList();
        int childCount = 0;

        if (entity.getChildren() != null && !entity.getChildren().isEmpty()) {
            childNodes = entity.getChildren().stream()
                    .sorted(Comparator.comparing(AccountsChart::getAccountChartNo))
                    .map(child -> toTreeNode(child, level + 1))
                    .collect(Collectors.toList());
            childCount = childNodes.size();
        }

        return AccountsChartTreeNode.builder()
                .accountChartPk(entity.getAccountChartPk())
                .accountChartNo(entity.getAccountChartNo())
                .accountChartName(entity.getAccountChartName())
                .accountType(entity.getAccountType())
                .level(level)
                .isActive(Boolean.TRUE.equals(entity.getIsActive()))
                .isLeaf(childNodes.isEmpty())
                .parentPk(entity.getParent() != null ? entity.getParent().getAccountChartPk() : null)
                .childCount(childCount)
                .children(childNodes)
                .build();
    }

    private String resolveParentName(AccountsChart entity) {
        if (entity.getParent() != null && Hibernate.isInitialized(entity.getParent())) {
            return entity.getParent().getAccountChartName();
        }
        return null;
    }

    private int computeLevel(AccountsChart entity) {
        int level = 0;
        AccountsChart current = entity;
        while (current.getParent() != null && Hibernate.isInitialized(current.getParent())) {
            level++;
            current = current.getParent();
        }
        return level;
    }
}
