-- ============================================================
-- Manual seed script for security tables
-- Schema: TEST
-- Run this AFTER manual_cleanup_security_test_data.sql
-- Fixes:
-- 1. Parent tables are inserted before child tables.
-- 2. Parent pages are inserted before child pages.
-- 3. CREATED_AT uses SYSTIMESTAMP to avoid NLS month parsing issues.
-- 4. UPDATED_AT / UPDATED_BY are set to NULL unless explicitly needed.
-- ============================================================

SET DEFINE OFF;

-- ============================================================
-- 1. PAGES FIRST
-- ============================================================

INSERT INTO TEST.SEC_PAGES (ID_PK,TENANT_ID,PAGE_CODE,NAME_AR,NAME_EN,ROUTE,ICON,MODULE,PARENT_ID_FK,DISPLAY_ORDER,IS_ACTIVE,DESCRIPTION,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY)
VALUES (15,'prod','USER','إدارة المستخدمين','User Management','/users','team','SECURITY',NULL,3,1,NULL,SYSTIMESTAMP,'admin',NULL,NULL);

INSERT INTO TEST.SEC_PAGES (ID_PK,TENANT_ID,PAGE_CODE,NAME_AR,NAME_EN,ROUTE,ICON,MODULE,PARENT_ID_FK,DISPLAY_ORDER,IS_ACTIVE,DESCRIPTION,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY)
VALUES (16,'prod','ROLE','إدارة صلاحيات الأدوار','Role Access Management1','/role-access','safety','SECURITY',NULL,3,1,NULL,SYSTIMESTAMP,'admin',NULL,NULL);

INSERT INTO TEST.SEC_PAGES (ID_PK,TENANT_ID,PAGE_CODE,NAME_AR,NAME_EN,ROUTE,ICON,MODULE,PARENT_ID_FK,DISPLAY_ORDER,IS_ACTIVE,DESCRIPTION,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY)
VALUES (18,'prod','MENU','إدارة القوائم','Menu Management','/menu-management','menu','SECURITY',NULL,4,0,NULL,SYSTIMESTAMP,'SYSTEM',NULL,NULL);

INSERT INTO TEST.SEC_PAGES (ID_PK,TENANT_ID,PAGE_CODE,NAME_AR,NAME_EN,ROUTE,ICON,MODULE,PARENT_ID_FK,DISPLAY_ORDER,IS_ACTIVE,DESCRIPTION,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY)
VALUES (19,'prod','PERMISSION','إدارة الصلاحيات','Permission Management','/permissions','safety','SECURITY',NULL,5,0,NULL,SYSTIMESTAMP,'SYSTEM',NULL,NULL);

INSERT INTO TEST.SEC_PAGES (ID_PK,TENANT_ID,PAGE_CODE,NAME_AR,NAME_EN,ROUTE,ICON,MODULE,PARENT_ID_FK,DISPLAY_ORDER,IS_ACTIVE,DESCRIPTION,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY)
VALUES (25,'prod','PAGE','إدارة الصفحات','Pages Registry','/pages','file','Security',NULL,40,1,NULL,SYSTIMESTAMP,'admin',NULL,NULL);

INSERT INTO TEST.SEC_PAGES (ID_PK,TENANT_ID,PAGE_CODE,NAME_AR,NAME_EN,ROUTE,ICON,MODULE,PARENT_ID_FK,DISPLAY_ORDER,IS_ACTIVE,DESCRIPTION,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY)
VALUES (45,'prod','TEST','تجربة','test','/test',NULL,'sec',NULL,10,0,NULL,SYSTIMESTAMP,'admin',NULL,NULL);

INSERT INTO TEST.SEC_PAGES (ID_PK,TENANT_ID,PAGE_CODE,NAME_AR,NAME_EN,ROUTE,ICON,MODULE,PARENT_ID_FK,DISPLAY_ORDER,IS_ACTIVE,DESCRIPTION,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY)
VALUES (65,'prod','PGE','fff','test','/us',NULL,NULL,NULL,10,0,NULL,SYSTIMESTAMP,'admin',NULL,NULL);

INSERT INTO TEST.SEC_PAGES (ID_PK,TENANT_ID,PAGE_CODE,NAME_AR,NAME_EN,ROUTE,ICON,MODULE,PARENT_ID_FK,DISPLAY_ORDER,IS_ACTIVE,DESCRIPTION,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY)
VALUES (85,'prod','EKLFLL','df,.','test','/users1212',NULL,NULL,NULL,10,0,NULL,SYSTIMESTAMP,'admin',NULL,NULL);

INSERT INTO TEST.SEC_PAGES (ID_PK,TENANT_ID,PAGE_CODE,NAME_AR,NAME_EN,ROUTE,ICON,MODULE,PARENT_ID_FK,DISPLAY_ORDER,IS_ACTIVE,DESCRIPTION,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY)
VALUES (106,'prod','MASTER_LOOKUP','قوائم البحث الرئيسية','Master Lookups','/master-data/master-lookups','search','MASTER_DATA',NULL,10,1,'Master lookup tables management - إدارة جداول البحث الرئيسية',SYSTIMESTAMP,'admin',NULL,NULL);

INSERT INTO TEST.SEC_PAGES (ID_PK,TENANT_ID,PAGE_CODE,NAME_AR,NAME_EN,ROUTE,ICON,MODULE,PARENT_ID_FK,DISPLAY_ORDER,IS_ACTIVE,DESCRIPTION,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY)
VALUES (125,'prod','GL','دفتر الأستاذ العام','General Ledger1','/finance/gl','ti ti-calculator','FINANCE',NULL,1,1,NULL,SYSTIMESTAMP,'SYSTEM',NULL,NULL);

INSERT INTO TEST.SEC_PAGES (ID_PK,TENANT_ID,PAGE_CODE,NAME_AR,NAME_EN,ROUTE,ICON,MODULE,PARENT_ID_FK,DISPLAY_ORDER,IS_ACTIVE,DESCRIPTION,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY)
VALUES (126,'prod','GL_ACCOUNT','دليل الحسابات','Chart of Accounts','/finance/gl/accounts','ti ti-list-tree','FINANCE',125,1,1,'Chart of Accounts management page',SYSTIMESTAMP,'SYSTEM',NULL,NULL);

INSERT INTO TEST.SEC_PAGES (ID_PK,TENANT_ID,PAGE_CODE,NAME_AR,NAME_EN,ROUTE,ICON,MODULE,PARENT_ID_FK,DISPLAY_ORDER,IS_ACTIVE,DESCRIPTION,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY)
VALUES (127,'prod','GL_RULE','قواعد المحاسبة','Accounting Rules','/finance/gl/rules','ti ti-scale','FINANCE',125,2,1,'Accounting Rules management page',SYSTIMESTAMP,'SYSTEM',NULL,NULL);

INSERT INTO TEST.SEC_PAGES (ID_PK,TENANT_ID,PAGE_CODE,NAME_AR,NAME_EN,ROUTE,ICON,MODULE,PARENT_ID_FK,DISPLAY_ORDER,IS_ACTIVE,DESCRIPTION,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY)
VALUES (145,'prod','GL_JOURNAL','القيود اليومية','Journal Entries','/finance/gl/journals','ti ti-notebook','FINANCE',125,3,1,'GL Journal Entries management page',SYSTIMESTAMP,'SYSTEM',NULL,NULL);

INSERT INTO TEST.SEC_PAGES (ID_PK,TENANT_ID,PAGE_CODE,NAME_AR,NAME_EN,ROUTE,ICON,MODULE,PARENT_ID_FK,DISPLAY_ORDER,IS_ACTIVE,DESCRIPTION,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY)
VALUES (165,'prod','GL_POSTING','قيود الترحيل','GL Postings','/finance/gl/postings','ti ti-file-export','FINANCE',125,4,1,'GL Postings management page',SYSTIMESTAMP,'SYSTEM',NULL,NULL);

-- ============================================================
-- 2. PERMISSIONS AFTER PAGES
-- ============================================================

INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (21,'PERM_MASTER_LOOKUP_VIEW','prod',106,'VIEW',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (22,'PERM_MASTER_LOOKUP_CREATE','prod',106,'CREATE',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (23,'PERM_MASTER_LOOKUP_UPDATE','prod',106,'UPDATE',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (24,'PERM_MASTER_LOOKUP_DELETE','prod',106,'DELETE',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (37,'PERM_USER_VIEW','prod',15,'VIEW',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (38,'PERM_USER_CREATE','prod',15,'CREATE',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (39,'PERM_USER_UPDATE','prod',15,'UPDATE',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (40,'PERM_USER_DELETE','prod',15,'DELETE',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (41,'PERM_ROLE_VIEW','prod',16,'VIEW',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (42,'PERM_ROLE_CREATE','prod',16,'CREATE',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (43,'PERM_ROLE_UPDATE','prod',16,'UPDATE',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (44,'PERM_ROLE_DELETE','prod',16,'DELETE',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (45,'PERM_PAGE_VIEW','prod',25,'VIEW',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (46,'PERM_PAGE_CREATE','prod',25,'CREATE',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (47,'PERM_PAGE_UPDATE','prod',25,'UPDATE',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (48,'PERM_PAGE_DELETE','prod',25,'DELETE',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (49,'PERM_MENU_VIEW','prod',18,'VIEW',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (50,'PERM_MENU_CREATE','prod',18,'CREATE',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (51,'PERM_MENU_UPDATE','prod',18,'UPDATE',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (52,'PERM_MENU_DELETE','prod',18,'DELETE',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (53,'PERM_PERMISSION_VIEW','prod',19,'VIEW',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (54,'PERM_PERMISSION_CREATE','prod',19,'CREATE',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (55,'PERM_PERMISSION_DELETE','prod',19,'DELETE',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (56,'PERM_GL_RULE_DELETE','prod',127,'DELETE',SYSTIMESTAMP,'SYSTEM',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (57,'PERM_ROLE_VIEW','prod',NULL,NULL,SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (58,'PERM_ROLE_CREATE','prod',NULL,NULL,SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (59,'PERM_ROLE_UPDATE','prod',NULL,NULL,SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (60,'PERM_ROLE_DELETE','prod',NULL,NULL,SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (61,'PERM_GL_RULE_VIEW','prod',127,'VIEW',SYSTIMESTAMP,'SYSTEM',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (62,'PERM_GL_RULE_CREATE','prod',127,'CREATE',SYSTIMESTAMP,'SYSTEM',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (63,'PERM_GL_RULE_UPDATE','prod',127,'UPDATE',SYSTIMESTAMP,'SYSTEM',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (65,'PERM_GL_ACCOUNT_VIEW','prod',126,'VIEW',SYSTIMESTAMP,'SYSTEM',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (66,'PERM_GL_ACCOUNT_CREATE','prod',126,'CREATE',SYSTIMESTAMP,'SYSTEM',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (67,'PERM_GL_ACCOUNT_UPDATE','prod',126,'UPDATE',SYSTIMESTAMP,'SYSTEM',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (68,'PERM_GL_ACCOUNT_DELETE','prod',126,'DELETE',SYSTIMESTAMP,'SYSTEM',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (77,'PERM_TEST_VIEW','prod',45,'VIEW',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (78,'PERM_TEST_CREATE','prod',45,'CREATE',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (79,'PERM_TEST_UPDATE','prod',45,'UPDATE',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (80,'PERM_TEST_DELETE','prod',45,'DELETE',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (81,'PERM_GL_JOURNAL_VIEW','prod',145,'VIEW',SYSTIMESTAMP,'SYSTEM',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (82,'PERM_GL_JOURNAL_CREATE','prod',145,'CREATE',SYSTIMESTAMP,'SYSTEM',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (83,'PERM_GL_JOURNAL_UPDATE','prod',145,'UPDATE',SYSTIMESTAMP,'SYSTEM',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (84,'PERM_GL_JOURNAL_DELETE','prod',145,'DELETE',SYSTIMESTAMP,'SYSTEM',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (85,'PERM_GL_JOURNAL_APPROVE','prod',145,NULL,SYSTIMESTAMP,'SYSTEM',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (86,'PERM_GL_JOURNAL_POST','prod',145,NULL,SYSTIMESTAMP,'SYSTEM',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (87,'PERM_GL_JOURNAL_REVERSE','prod',145,NULL,SYSTIMESTAMP,'SYSTEM',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (88,'PERM_GL_JOURNAL_CANCEL','prod',145,NULL,SYSTIMESTAMP,'SYSTEM',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (97,'PERM_PGE_VIEW','prod',65,'VIEW',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (98,'PERM_PGE_CREATE','prod',65,'CREATE',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (99,'PERM_PGE_UPDATE','prod',65,'UPDATE',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (100,'PERM_PGE_DELETE','prod',65,'DELETE',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (101,'PERM_GL_POSTING_VIEW','prod',165,'VIEW',SYSTIMESTAMP,'SYSTEM',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (103,'PERM_GL_POSTING_CREATE','prod',165,'CREATE',SYSTIMESTAMP,'SYSTEM',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (104,'PERM_GL_POSTING_UPDATE','prod',165,'UPDATE',SYSTIMESTAMP,'SYSTEM',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (105,'PERM_GL_POSTING_DELETE','prod',165,'DELETE',SYSTIMESTAMP,'SYSTEM',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (117,'PERM_EKLFLL_VIEW','prod',85,'VIEW',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (118,'PERM_EKLFLL_CREATE','prod',85,'CREATE',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (119,'PERM_EKLFLL_UPDATE','prod',85,'UPDATE',SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.PERMISSIONS (ID,NAME,TENANT_ID,PAGE_ID_FK,PERMISSION_TYPE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (120,'PERM_EKLFLL_DELETE','prod',85,'DELETE',SYSTIMESTAMP,'system',NULL,NULL);

-- ============================================================
-- 3. ROLES AND USERS
-- ============================================================

INSERT INTO TEST.ROLES (ID,NAME,TENANT_ID,IS_ACTIVE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (1,'ROLE_ADMIN','prod',1,SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.ROLES (ID,NAME,TENANT_ID,IS_ACTIVE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (4,'ROLE_USER','prod',1,SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.ROLES (ID,NAME,TENANT_ID,IS_ACTIVE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (21,'TEST123','prod',1,SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.ROLES (ID,NAME,TENANT_ID,IS_ACTIVE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (24,'test','prod',0,SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.ROLES (ID,NAME,TENANT_ID,IS_ACTIVE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (41,'E2EROLE1769798801365','prod',1,SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.ROLES (ID,NAME,TENANT_ID,IS_ACTIVE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (42,'E2EPERM1769798802489','prod',1,SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.ROLES (ID,NAME,TENANT_ID,IS_ACTIVE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (44,'E2EFILTER1769798862429','prod',1,SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.ROLES (ID,NAME,TENANT_ID,IS_ACTIVE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (45,'E2ETOGGLE1769798863646','prod',1,SYSTIMESTAMP,'system',NULL,NULL);
INSERT INTO TEST.ROLES (ID,NAME,TENANT_ID,IS_ACTIVE,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (46,'E2EFILTER1769798862429EXTRA','prod',0,SYSTIMESTAMP,'system',NULL,NULL);

INSERT INTO TEST.USERS (ID,CREATED_AT,ENABLED,PASSWORD,TENANT_ID,USERNAME,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (1,SYSTIMESTAMP,1,'$2a$10$yf8kXdkwPu.OnXlvp8lHXO5kkjB0qEKPuK26CBqCWcLs71mTsUDK2','prod','admin','system',NULL,NULL);
INSERT INTO TEST.USERS (ID,CREATED_AT,ENABLED,PASSWORD,TENANT_ID,USERNAME,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (2,SYSTIMESTAMP,1,'$2a$10$lGX/ES3hwtBQWjCdTT4/4.GoYM6oudGCl4q2w3tfctpqhsupyuSsS','prod','user','system',NULL,NULL);
INSERT INTO TEST.USERS (ID,CREATED_AT,ENABLED,PASSWORD,TENANT_ID,USERNAME,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (61,SYSTIMESTAMP,1,'$2a$10$T3Kq0cF7PKPdqlHKTqAAteW7HHRaBtr2SF64QBHbYKchER3jDQORO','prod','mohamed','system',NULL,NULL);
INSERT INTO TEST.USERS (ID,CREATED_AT,ENABLED,PASSWORD,TENANT_ID,USERNAME,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (81,SYSTIMESTAMP,1,'$2a$10$XA683ZJ1zB9CwPE1v27Rx.67hu5hj.Tsvcx7bILSLG7fLLa/t2Ku6','prod','ttttttttttt','admin',NULL,NULL);
INSERT INTO TEST.USERS (ID,CREATED_AT,ENABLED,PASSWORD,TENANT_ID,USERNAME,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (101,SYSTIMESTAMP,1,'$2a$10$bj/.uZoimNtXuWOI2XiH.OKQQZ96D.oKUr1jhNqYOo7Q2NBrkzWx.','prod','kjkkkkk','admin',NULL,NULL);
INSERT INTO TEST.USERS (ID,CREATED_AT,ENABLED,PASSWORD,TENANT_ID,USERNAME,CREATED_BY,UPDATED_AT,UPDATED_BY) VALUES (121,SYSTIMESTAMP,1,'$2a$10$fBmNFuXoudS02FBmrIUT.OK.MXF2rU2uHhj7M12sj45sZViwuL8/a','prod','test_2','admin',NULL,NULL);

-- ============================================================
-- 4. JOIN TABLES LAST
-- ============================================================

INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,21);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,22);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,23);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,24);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,37);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,38);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,39);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,40);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,41);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,42);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,43);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,44);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,45);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,46);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,47);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,48);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,49);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,50);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,51);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,52);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,53);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,54);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,55);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,56);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,61);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,62);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,63);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,65);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,66);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,67);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,68);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,77);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,81);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,82);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,83);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,84);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,101);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,103);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,104);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,105);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (1,117);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (21,37);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (21,41);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (21,45);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (21,49);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (21,53);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (21,77);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (24,37);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (24,41);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (24,45);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (24,49);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (24,50);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (24,51);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (24,52);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (24,53);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (24,77);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (42,21);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (42,22);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (42,23);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (42,24);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (42,37);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (42,41);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (42,45);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (42,49);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (42,53);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (42,77);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (45,37);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (45,41);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (45,45);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (45,49);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (45,53);
INSERT INTO TEST.ROLE_PERMISSIONS (ROLE_ID,PERM_ID) VALUES (45,77);

INSERT INTO TEST.USER_ROLES (USER_ID,ROLE_ID) VALUES (1,1);
INSERT INTO TEST.USER_ROLES (USER_ID,ROLE_ID) VALUES (1,4);
INSERT INTO TEST.USER_ROLES (USER_ID,ROLE_ID) VALUES (61,1);
INSERT INTO TEST.USER_ROLES (USER_ID,ROLE_ID) VALUES (81,4);
INSERT INTO TEST.USER_ROLES (USER_ID,ROLE_ID) VALUES (101,4);
INSERT INTO TEST.USER_ROLES (USER_ID,ROLE_ID) VALUES (121,1);

COMMIT;
