-- ============================================================
-- Test Data: ACC_POSTING_MST + ACC_POSTING_DTL — Full Insert
-- Run AFTER V12 migration
-- ============================================================
-- Covers all lifecycle statuses with realistic SALES/PURCHASE scenarios.
-- Accounts referenced (adjust if your chart differs):
--   85 = Accounts Receivable (ذمم مدينة)
--   82 = Sales Revenue (إيرادات المبيعات)
--   18 = Cash (النقدية)
--   14 = Purchases (المشتريات)
--    8 = Accounts Payable (ذمم دائنة)
--   89 = VAT Output (ض.ق.م مخرجات)
-- ============================================================

-- ================================================================
-- STEP 1: Clean existing test data (optional — uncomment if needed)
-- ================================================================
-- DELETE FROM ACC_POSTING_DTL WHERE POSTING_ID_FK IN (1,2,3,4,5,6,7);
-- DELETE FROM ACC_POSTING_MST WHERE POSTING_ID IN (1,2,3,4,5,6,7);

-- ================================================================
-- STEP 2: Insert ACC_POSTING_MST
-- ================================================================

-- Posting 1: SALES/INVOICE — DRAFT (not yet ready for GL)
INSERT INTO ACC_POSTING_MST (POSTING_ID, BRANCH_ID_FK, COMPANY_ID_FK, CURRENCY_CODE, DOC_DATE, ERROR_MESSAGE, FIN_JOURNAL_ID_FK, REVERSAL_POSTING_ID_FK, SOURCE_DOC_ID, SOURCE_DOC_NO, SOURCE_DOC_TYPE, SOURCE_MODULE, STATUS, TOTAL_AMOUNT, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (1, NULL, 1, 'SAR', DATE '2026-01-10', NULL, NULL, NULL, 1, 'INV-2026-0001', 'INVOICE', 'SALES', 'DRAFT', 3000.00, SYSTIMESTAMP, 'sales_user', NULL, NULL);

-- Posting 2: SALES/INVOICE — READY_FOR_GL (ready to generate journal)
INSERT INTO ACC_POSTING_MST (POSTING_ID, BRANCH_ID_FK, COMPANY_ID_FK, CURRENCY_CODE, DOC_DATE, ERROR_MESSAGE, FIN_JOURNAL_ID_FK, REVERSAL_POSTING_ID_FK, SOURCE_DOC_ID, SOURCE_DOC_NO, SOURCE_DOC_TYPE, SOURCE_MODULE, STATUS, TOTAL_AMOUNT, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (2, NULL, 1, 'SAR', DATE '2026-01-16', NULL, NULL, NULL, 2, 'INV-2026-0002', 'INVOICE', 'SALES', 'READY_FOR_GL', 5750.00, SYSTIMESTAMP, 'sales_user', NULL, NULL);

-- Posting 3: SALES/CREDIT_NOTE — READY_FOR_GL
INSERT INTO ACC_POSTING_MST (POSTING_ID, BRANCH_ID_FK, COMPANY_ID_FK, CURRENCY_CODE, DOC_DATE, ERROR_MESSAGE, FIN_JOURNAL_ID_FK, REVERSAL_POSTING_ID_FK, SOURCE_DOC_ID, SOURCE_DOC_NO, SOURCE_DOC_TYPE, SOURCE_MODULE, STATUS, TOTAL_AMOUNT, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (3, NULL, 1, 'SAR', DATE '2026-02-01', NULL, NULL, NULL, 3, 'CN-2026-0001', 'CREDIT_NOTE', 'SALES', 'READY_FOR_GL', 2300.00, SYSTIMESTAMP, 'sales_user', NULL, NULL);

-- Posting 4: SALES/RECEIPT — READY_FOR_GL
INSERT INTO ACC_POSTING_MST (POSTING_ID, BRANCH_ID_FK, COMPANY_ID_FK, CURRENCY_CODE, DOC_DATE, ERROR_MESSAGE, FIN_JOURNAL_ID_FK, REVERSAL_POSTING_ID_FK, SOURCE_DOC_ID, SOURCE_DOC_NO, SOURCE_DOC_TYPE, SOURCE_MODULE, STATUS, TOTAL_AMOUNT, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (4, NULL, 1, 'SAR', DATE '2026-02-10', NULL, NULL, NULL, 4, 'RCT-2026-0001', 'RECEIPT', 'SALES', 'READY_FOR_GL', 5000.00, SYSTIMESTAMP, 'sales_user', NULL, NULL);

-- Posting 5: PURCHASE/INVOICE — READY_FOR_GL
INSERT INTO ACC_POSTING_MST (POSTING_ID, BRANCH_ID_FK, COMPANY_ID_FK, CURRENCY_CODE, DOC_DATE, ERROR_MESSAGE, FIN_JOURNAL_ID_FK, REVERSAL_POSTING_ID_FK, SOURCE_DOC_ID, SOURCE_DOC_NO, SOURCE_DOC_TYPE, SOURCE_MODULE, STATUS, TOTAL_AMOUNT, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (5, NULL, 1, 'SAR', DATE '2026-02-15', NULL, NULL, NULL, 5, 'PUR-2026-0001', 'INVOICE', 'PURCHASE', 'READY_FOR_GL', 9200.00, SYSTIMESTAMP, 'purchase_user', NULL, NULL);

-- Posting 6: SALES/INVOICE — ERROR (failed previous generation attempt)
INSERT INTO ACC_POSTING_MST (POSTING_ID, BRANCH_ID_FK, COMPANY_ID_FK, CURRENCY_CODE, DOC_DATE, ERROR_MESSAGE, FIN_JOURNAL_ID_FK, REVERSAL_POSTING_ID_FK, SOURCE_DOC_ID, SOURCE_DOC_NO, SOURCE_DOC_TYPE, SOURCE_MODULE, STATUS, TOTAL_AMOUNT, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (6, NULL, 1, 'SAR', DATE '2026-03-01', 'GL_POSTING_UNBALANCED', NULL, NULL, 6, 'INV-2026-0003', 'INVOICE', 'SALES', 'ERROR', 1500.00, SYSTIMESTAMP, 'sales_user', SYSTIMESTAMP, 'SYSTEM');

-- Posting 7: SALES/INVOICE — READY_FOR_GL (second company)
INSERT INTO ACC_POSTING_MST (POSTING_ID, BRANCH_ID_FK, COMPANY_ID_FK, CURRENCY_CODE, DOC_DATE, ERROR_MESSAGE, FIN_JOURNAL_ID_FK, REVERSAL_POSTING_ID_FK, SOURCE_DOC_ID, SOURCE_DOC_NO, SOURCE_DOC_TYPE, SOURCE_MODULE, STATUS, TOTAL_AMOUNT, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (7, NULL, 2, 'SAR', DATE '2026-03-10', NULL, NULL, NULL, 7, 'INV-2026-0004', 'INVOICE', 'SALES', 'READY_FOR_GL', 4600.00, SYSTIMESTAMP, 'sales_user', NULL, NULL);

-- ================================================================
-- STEP 3: Insert ACC_POSTING_DTL
-- ================================================================

-- ── Posting 1 Details (DRAFT — SALES/INVOICE 3000) ──────────
INSERT INTO ACC_POSTING_DTL (POSTING_DTL_ID, POSTING_ID_FK, LINE_NO, AMOUNT, BUSINESS_SIDE, SIGN, DESCRIPTION, CUSTOMER_ID_FK, SUPPLIER_ID_FK, COST_CENTER_ID_FK, CONTRACT_ID_FK, ITEM_ID_FK, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACC_POSTING_DTL_SEQ.NEXTVAL, 1, 1, 3000.00, 'RECEIVABLE', 1, N'إجمالي الفاتورة', 100, NULL, NULL, NULL, NULL, SYSTIMESTAMP, 'sales_user', NULL, NULL);

INSERT INTO ACC_POSTING_DTL (POSTING_DTL_ID, POSTING_ID_FK, LINE_NO, AMOUNT, BUSINESS_SIDE, SIGN, DESCRIPTION, CUSTOMER_ID_FK, SUPPLIER_ID_FK, COST_CENTER_ID_FK, CONTRACT_ID_FK, ITEM_ID_FK, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACC_POSTING_DTL_SEQ.NEXTVAL, 1, 2, 2608.70, 'REVENUE', 1, N'قيمة المبيعات', 100, NULL, NULL, NULL, NULL, SYSTIMESTAMP, 'sales_user', NULL, NULL);

INSERT INTO ACC_POSTING_DTL (POSTING_DTL_ID, POSTING_ID_FK, LINE_NO, AMOUNT, BUSINESS_SIDE, SIGN, DESCRIPTION, CUSTOMER_ID_FK, SUPPLIER_ID_FK, COST_CENTER_ID_FK, CONTRACT_ID_FK, ITEM_ID_FK, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACC_POSTING_DTL_SEQ.NEXTVAL, 1, 3, 391.30, 'VAT_OUTPUT', 1, N'ضريبة القيمة المضافة 15%', 100, NULL, NULL, NULL, NULL, SYSTIMESTAMP, 'sales_user', NULL, NULL);

-- ── Posting 2 Details (READY_FOR_GL — SALES/INVOICE 5750) ───
INSERT INTO ACC_POSTING_DTL (POSTING_DTL_ID, POSTING_ID_FK, LINE_NO, AMOUNT, BUSINESS_SIDE, SIGN, DESCRIPTION, CUSTOMER_ID_FK, SUPPLIER_ID_FK, COST_CENTER_ID_FK, CONTRACT_ID_FK, ITEM_ID_FK, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACC_POSTING_DTL_SEQ.NEXTVAL, 2, 1, 5750.00, 'RECEIVABLE', 1, N'إجمالي الفاتورة شامل الضريبة', 101, NULL, NULL, NULL, NULL, SYSTIMESTAMP, 'sales_user', NULL, NULL);

INSERT INTO ACC_POSTING_DTL (POSTING_DTL_ID, POSTING_ID_FK, LINE_NO, AMOUNT, BUSINESS_SIDE, SIGN, DESCRIPTION, CUSTOMER_ID_FK, SUPPLIER_ID_FK, COST_CENTER_ID_FK, CONTRACT_ID_FK, ITEM_ID_FK, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACC_POSTING_DTL_SEQ.NEXTVAL, 2, 2, 5000.00, 'REVENUE', 1, N'قيمة المبيعات', 101, NULL, NULL, NULL, NULL, SYSTIMESTAMP, 'sales_user', NULL, NULL);

INSERT INTO ACC_POSTING_DTL (POSTING_DTL_ID, POSTING_ID_FK, LINE_NO, AMOUNT, BUSINESS_SIDE, SIGN, DESCRIPTION, CUSTOMER_ID_FK, SUPPLIER_ID_FK, COST_CENTER_ID_FK, CONTRACT_ID_FK, ITEM_ID_FK, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACC_POSTING_DTL_SEQ.NEXTVAL, 2, 3, 750.00, 'VAT_OUTPUT', 1, N'ضريبة القيمة المضافة 15%', 101, NULL, NULL, NULL, NULL, SYSTIMESTAMP, 'sales_user', NULL, NULL);

-- ── Posting 3 Details (READY_FOR_GL — SALES/CREDIT_NOTE 2300) ─
INSERT INTO ACC_POSTING_DTL (POSTING_DTL_ID, POSTING_ID_FK, LINE_NO, AMOUNT, BUSINESS_SIDE, SIGN, DESCRIPTION, CUSTOMER_ID_FK, SUPPLIER_ID_FK, COST_CENTER_ID_FK, CONTRACT_ID_FK, ITEM_ID_FK, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACC_POSTING_DTL_SEQ.NEXTVAL, 3, 1, 2000.00, 'RETURNS', -1, N'مرتجعات مبيعات', 100, NULL, NULL, NULL, NULL, SYSTIMESTAMP, 'sales_user', NULL, NULL);

INSERT INTO ACC_POSTING_DTL (POSTING_DTL_ID, POSTING_ID_FK, LINE_NO, AMOUNT, BUSINESS_SIDE, SIGN, DESCRIPTION, CUSTOMER_ID_FK, SUPPLIER_ID_FK, COST_CENTER_ID_FK, CONTRACT_ID_FK, ITEM_ID_FK, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACC_POSTING_DTL_SEQ.NEXTVAL, 3, 2, 2300.00, 'RECEIVABLE', -1, N'تخفيض ذمم مدينة', 100, NULL, NULL, NULL, NULL, SYSTIMESTAMP, 'sales_user', NULL, NULL);

INSERT INTO ACC_POSTING_DTL (POSTING_DTL_ID, POSTING_ID_FK, LINE_NO, AMOUNT, BUSINESS_SIDE, SIGN, DESCRIPTION, CUSTOMER_ID_FK, SUPPLIER_ID_FK, COST_CENTER_ID_FK, CONTRACT_ID_FK, ITEM_ID_FK, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACC_POSTING_DTL_SEQ.NEXTVAL, 3, 3, 300.00, 'VAT_OUTPUT', -1, N'تعديل ضريبة القيمة المضافة', 100, NULL, NULL, NULL, NULL, SYSTIMESTAMP, 'sales_user', NULL, NULL);

-- ── Posting 4 Details (READY_FOR_GL — SALES/RECEIPT 5000) ───
INSERT INTO ACC_POSTING_DTL (POSTING_DTL_ID, POSTING_ID_FK, LINE_NO, AMOUNT, BUSINESS_SIDE, SIGN, DESCRIPTION, CUSTOMER_ID_FK, SUPPLIER_ID_FK, COST_CENTER_ID_FK, CONTRACT_ID_FK, ITEM_ID_FK, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACC_POSTING_DTL_SEQ.NEXTVAL, 4, 1, 5000.00, 'CASH', 1, N'مقبوضات نقدية', 100, NULL, NULL, NULL, NULL, SYSTIMESTAMP, 'sales_user', NULL, NULL);

INSERT INTO ACC_POSTING_DTL (POSTING_DTL_ID, POSTING_ID_FK, LINE_NO, AMOUNT, BUSINESS_SIDE, SIGN, DESCRIPTION, CUSTOMER_ID_FK, SUPPLIER_ID_FK, COST_CENTER_ID_FK, CONTRACT_ID_FK, ITEM_ID_FK, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACC_POSTING_DTL_SEQ.NEXTVAL, 4, 2, 5000.00, 'RECEIVABLE', -1, N'تسوية ذمم مدينة', 100, NULL, NULL, NULL, NULL, SYSTIMESTAMP, 'sales_user', NULL, NULL);

-- ── Posting 5 Details (READY_FOR_GL — PURCHASE/INVOICE 9200) ─
INSERT INTO ACC_POSTING_DTL (POSTING_DTL_ID, POSTING_ID_FK, LINE_NO, AMOUNT, BUSINESS_SIDE, SIGN, DESCRIPTION, CUSTOMER_ID_FK, SUPPLIER_ID_FK, COST_CENTER_ID_FK, CONTRACT_ID_FK, ITEM_ID_FK, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACC_POSTING_DTL_SEQ.NEXTVAL, 5, 1, 8000.00, 'PURCHASES', 1, N'مشتريات بضاعة', NULL, 200, NULL, NULL, NULL, SYSTIMESTAMP, 'purchase_user', NULL, NULL);

INSERT INTO ACC_POSTING_DTL (POSTING_DTL_ID, POSTING_ID_FK, LINE_NO, AMOUNT, BUSINESS_SIDE, SIGN, DESCRIPTION, CUSTOMER_ID_FK, SUPPLIER_ID_FK, COST_CENTER_ID_FK, CONTRACT_ID_FK, ITEM_ID_FK, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACC_POSTING_DTL_SEQ.NEXTVAL, 5, 2, 1200.00, 'VAT_INPUT', 1, N'ضريبة مدخلات 15%', NULL, 200, NULL, NULL, NULL, SYSTIMESTAMP, 'purchase_user', NULL, NULL);

INSERT INTO ACC_POSTING_DTL (POSTING_DTL_ID, POSTING_ID_FK, LINE_NO, AMOUNT, BUSINESS_SIDE, SIGN, DESCRIPTION, CUSTOMER_ID_FK, SUPPLIER_ID_FK, COST_CENTER_ID_FK, CONTRACT_ID_FK, ITEM_ID_FK, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACC_POSTING_DTL_SEQ.NEXTVAL, 5, 3, 9200.00, 'PAYABLE', -1, N'ذمم دائنة مورد', NULL, 200, NULL, NULL, NULL, SYSTIMESTAMP, 'purchase_user', NULL, NULL);

-- ── Posting 6 Details (ERROR — SALES/INVOICE 1500, unbalanced) ─
INSERT INTO ACC_POSTING_DTL (POSTING_DTL_ID, POSTING_ID_FK, LINE_NO, AMOUNT, BUSINESS_SIDE, SIGN, DESCRIPTION, CUSTOMER_ID_FK, SUPPLIER_ID_FK, COST_CENTER_ID_FK, CONTRACT_ID_FK, ITEM_ID_FK, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACC_POSTING_DTL_SEQ.NEXTVAL, 6, 1, 1500.00, 'RECEIVABLE', 1, N'ذمم مدينة (خطأ في التوازن)', 102, NULL, NULL, NULL, NULL, SYSTIMESTAMP, 'sales_user', NULL, NULL);

-- ── Posting 7 Details (READY_FOR_GL — SALES/INVOICE 4600, company 2) ─
INSERT INTO ACC_POSTING_DTL (POSTING_DTL_ID, POSTING_ID_FK, LINE_NO, AMOUNT, BUSINESS_SIDE, SIGN, DESCRIPTION, CUSTOMER_ID_FK, SUPPLIER_ID_FK, COST_CENTER_ID_FK, CONTRACT_ID_FK, ITEM_ID_FK, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACC_POSTING_DTL_SEQ.NEXTVAL, 7, 1, 4600.00, 'RECEIVABLE', 1, N'إجمالي الفاتورة شامل الضريبة', 103, NULL, NULL, NULL, NULL, SYSTIMESTAMP, 'sales_user', NULL, NULL);

INSERT INTO ACC_POSTING_DTL (POSTING_DTL_ID, POSTING_ID_FK, LINE_NO, AMOUNT, BUSINESS_SIDE, SIGN, DESCRIPTION, CUSTOMER_ID_FK, SUPPLIER_ID_FK, COST_CENTER_ID_FK, CONTRACT_ID_FK, ITEM_ID_FK, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACC_POSTING_DTL_SEQ.NEXTVAL, 7, 2, 4000.00, 'REVENUE', 1, N'قيمة المبيعات', 103, NULL, NULL, NULL, NULL, SYSTIMESTAMP, 'sales_user', NULL, NULL);

INSERT INTO ACC_POSTING_DTL (POSTING_DTL_ID, POSTING_ID_FK, LINE_NO, AMOUNT, BUSINESS_SIDE, SIGN, DESCRIPTION, CUSTOMER_ID_FK, SUPPLIER_ID_FK, COST_CENTER_ID_FK, CONTRACT_ID_FK, ITEM_ID_FK, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACC_POSTING_DTL_SEQ.NEXTVAL, 7, 3, 600.00, 'VAT_OUTPUT', 1, N'ضريبة القيمة المضافة 15%', 103, NULL, NULL, NULL, NULL, SYSTIMESTAMP, 'sales_user', NULL, NULL);

COMMIT;

-- ================================================================
-- VERIFICATION QUERIES
-- ================================================================

-- 1. All postings with status and detail count:
SELECT m.POSTING_ID, m.SOURCE_MODULE, m.SOURCE_DOC_TYPE, m.SOURCE_DOC_NO,
       m.STATUS, m.TOTAL_AMOUNT, m.FIN_JOURNAL_ID_FK,
       (SELECT COUNT(*) FROM ACC_POSTING_DTL d WHERE d.POSTING_ID_FK = m.POSTING_ID) AS DETAIL_COUNT
  FROM ACC_POSTING_MST m
 ORDER BY m.POSTING_ID;

-- 2. All detail lines:
SELECT d.POSTING_DTL_ID, d.POSTING_ID_FK, d.LINE_NO, d.BUSINESS_SIDE,
       d.AMOUNT, d.SIGN, d.CUSTOMER_ID_FK, d.SUPPLIER_ID_FK, d.DESCRIPTION
  FROM ACC_POSTING_DTL d
 ORDER BY d.POSTING_ID_FK, d.LINE_NO;
