-- ============================================================
-- ERP System — Realistic Test Data
-- Oracle Database — Schema: TEST/TEST
-- ============================================================
-- Run AFTER V0__full_schema_create.sql
-- ============================================================
-- BCrypt passwords generated for: P@ssw0rd123
-- BCrypt hash: $2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy
-- ============================================================

-- ============================================================
-- 1. SECURITY — Users, Roles, Permissions, Pages
-- ============================================================

-- 1.1 Users (password = P@ssw0rd123 for all)
INSERT INTO USERS (ID, USERNAME, PASSWORD, ENABLED, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (1, 'admin',      '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 1, 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO USERS (ID, USERNAME, PASSWORD, ENABLED, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (2, 'ahmed.mahmoud', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 1, 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO USERS (ID, USERNAME, PASSWORD, ENABLED, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (3, 'sara.ali',     '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 1, 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO USERS (ID, USERNAME, PASSWORD, ENABLED, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (4, 'omar.hassan',  '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 1, 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO USERS (ID, USERNAME, PASSWORD, ENABLED, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (5, 'fatma.khalil', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 0, 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- 1.2 Roles
INSERT INTO ROLES (ID, NAME, IS_ACTIVE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (1, 'مدير النظام',       1, 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO ROLES (ID, NAME, IS_ACTIVE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (2, 'محاسب',             1, 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO ROLES (ID, NAME, IS_ACTIVE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (3, 'مدير مالي',         1, 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO ROLES (ID, NAME, IS_ACTIVE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (4, 'مستخدم عادي',       1, 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO ROLES (ID, NAME, IS_ACTIVE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (5, 'مدقق',              0, 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- 1.3 User ↔ Role assignments
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (1, 1); -- admin → مدير النظام
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (2, 2); -- ahmed → محاسب
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (2, 4); -- ahmed → مستخدم عادي
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (3, 3); -- sara → مدير مالي
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (4, 4); -- omar → مستخدم عادي

-- 1.4 Pages (UI Screens)
INSERT INTO SEC_PAGES (ID_PK, PAGE_CODE, NAME_AR, NAME_EN, ROUTE, ICON, MODULE, PARENT_ID_FK, DISPLAY_ORDER, IS_ACTIVE, DESCRIPTION, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (SEC_PAGES_SEQ.NEXTVAL, 'DASHBOARD',      'لوحة التحكم',           'Dashboard',            '/dashboard',                   'feather:home',         'GENERAL',   NULL, 1, 1, 'الصفحة الرئيسية',          'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO SEC_PAGES (ID_PK, PAGE_CODE, NAME_AR, NAME_EN, ROUTE, ICON, MODULE, PARENT_ID_FK, DISPLAY_ORDER, IS_ACTIVE, DESCRIPTION, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (SEC_PAGES_SEQ.NEXTVAL, 'USER_MANAGEMENT', 'إدارة المستخدمين',     'User Management',      '/security/users',              'feather:users',        'SECURITY',  NULL, 2, 1, 'إدارة حسابات المستخدمين',  'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO SEC_PAGES (ID_PK, PAGE_CODE, NAME_AR, NAME_EN, ROUTE, ICON, MODULE, PARENT_ID_FK, DISPLAY_ORDER, IS_ACTIVE, DESCRIPTION, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (SEC_PAGES_SEQ.NEXTVAL, 'ROLE_ACCESS',     'إدارة الصلاحيات',      'Role Access',          '/security/roles',              'feather:shield',       'SECURITY',  NULL, 3, 1, 'إدارة الأدوار والصلاحيات', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO SEC_PAGES (ID_PK, PAGE_CODE, NAME_AR, NAME_EN, ROUTE, ICON, MODULE, PARENT_ID_FK, DISPLAY_ORDER, IS_ACTIVE, DESCRIPTION, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (SEC_PAGES_SEQ.NEXTVAL, 'PAGES_REGISTRY',  'سجل الصفحات',          'Pages Registry',       '/security/pages',              'feather:layout',       'SECURITY',  NULL, 4, 1, 'تسجيل صفحات النظام',       'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO SEC_PAGES (ID_PK, PAGE_CODE, NAME_AR, NAME_EN, ROUTE, ICON, MODULE, PARENT_ID_FK, DISPLAY_ORDER, IS_ACTIVE, DESCRIPTION, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (SEC_PAGES_SEQ.NEXTVAL, 'MASTER_LOOKUP',   'القوائم المرجعية',     'Master Lookups',       '/masterdata/lookups',          'feather:list',         'MASTERDATA', NULL, 5, 1, 'القوائم المرجعية الرئيسية','DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO SEC_PAGES (ID_PK, PAGE_CODE, NAME_AR, NAME_EN, ROUTE, ICON, MODULE, PARENT_ID_FK, DISPLAY_ORDER, IS_ACTIVE, DESCRIPTION, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (SEC_PAGES_SEQ.NEXTVAL, 'ACTIVITY',        'الأنشطة',              'Activities',           '/masterdata/activities',       'feather:activity',     'MASTERDATA', NULL, 6, 1, 'إدارة الأنشطة',            'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO SEC_PAGES (ID_PK, PAGE_CODE, NAME_AR, NAME_EN, ROUTE, ICON, MODULE, PARENT_ID_FK, DISPLAY_ORDER, IS_ACTIVE, DESCRIPTION, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (SEC_PAGES_SEQ.NEXTVAL, 'GL_ACCOUNTS',     'شجرة الحسابات',        'Chart of Accounts',    '/finance/gl/accounts',         'feather:git-branch',   'FINANCE',   NULL, 7, 1, 'شجرة الحسابات المحاسبية', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO SEC_PAGES (ID_PK, PAGE_CODE, NAME_AR, NAME_EN, ROUTE, ICON, MODULE, PARENT_ID_FK, DISPLAY_ORDER, IS_ACTIVE, DESCRIPTION, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (SEC_PAGES_SEQ.NEXTVAL, 'GL_JOURNALS',     'القيود اليومية',       'Journal Entries',      '/finance/gl/journals',         'feather:book-open',    'FINANCE',   NULL, 8, 1, 'القيود المحاسبية اليومية','DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO SEC_PAGES (ID_PK, PAGE_CODE, NAME_AR, NAME_EN, ROUTE, ICON, MODULE, PARENT_ID_FK, DISPLAY_ORDER, IS_ACTIVE, DESCRIPTION, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (SEC_PAGES_SEQ.NEXTVAL, 'GL_RULES',        'قواعد الترحيل',        'Posting Rules',        '/finance/gl/rules',            'feather:settings',     'FINANCE',   NULL, 9, 1, 'قواعد الترحيل المحاسبي',  'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO SEC_PAGES (ID_PK, PAGE_CODE, NAME_AR, NAME_EN, ROUTE, ICON, MODULE, PARENT_ID_FK, DISPLAY_ORDER, IS_ACTIVE, DESCRIPTION, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (SEC_PAGES_SEQ.NEXTVAL, 'GL_POSTINGS',     'الترحيلات',            'Postings',             '/finance/gl/postings',         'feather:send',         'FINANCE',   NULL, 10, 1, 'عمليات الترحيل المالي',   'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- 1.5 Permissions (4 CRUD per page)
-- We'll use variables for page IDs. Assuming pages start at ID_PK=1 sequentially.
-- DASHBOARD (page 1)
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ( 1, 'PERM_DASHBOARD_VIEW',   1, 'VIEW',   'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ( 2, 'PERM_DASHBOARD_CREATE', 1, 'CREATE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ( 3, 'PERM_DASHBOARD_UPDATE', 1, 'UPDATE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ( 4, 'PERM_DASHBOARD_DELETE', 1, 'DELETE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- USER_MANAGEMENT (page 2)
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ( 5, 'PERM_USER_MANAGEMENT_VIEW',   2, 'VIEW',   'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ( 6, 'PERM_USER_MANAGEMENT_CREATE', 2, 'CREATE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ( 7, 'PERM_USER_MANAGEMENT_UPDATE', 2, 'UPDATE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ( 8, 'PERM_USER_MANAGEMENT_DELETE', 2, 'DELETE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- ROLE_ACCESS (page 3)
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES ( 9, 'PERM_ROLE_ACCESS_VIEW',   3, 'VIEW',   'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (10, 'PERM_ROLE_ACCESS_CREATE', 3, 'CREATE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (11, 'PERM_ROLE_ACCESS_UPDATE', 3, 'UPDATE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (12, 'PERM_ROLE_ACCESS_DELETE', 3, 'DELETE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- PAGES_REGISTRY (page 4)
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (13, 'PERM_PAGES_REGISTRY_VIEW',   4, 'VIEW',   'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (14, 'PERM_PAGES_REGISTRY_CREATE', 4, 'CREATE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (15, 'PERM_PAGES_REGISTRY_UPDATE', 4, 'UPDATE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (16, 'PERM_PAGES_REGISTRY_DELETE', 4, 'DELETE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- MASTER_LOOKUP (page 5)
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (17, 'PERM_MASTER_LOOKUP_VIEW',   5, 'VIEW',   'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (18, 'PERM_MASTER_LOOKUP_CREATE', 5, 'CREATE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (19, 'PERM_MASTER_LOOKUP_UPDATE', 5, 'UPDATE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (20, 'PERM_MASTER_LOOKUP_DELETE', 5, 'DELETE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- ACTIVITY (page 6)
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (21, 'PERM_ACTIVITY_VIEW',   6, 'VIEW',   'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (22, 'PERM_ACTIVITY_CREATE', 6, 'CREATE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (23, 'PERM_ACTIVITY_UPDATE', 6, 'UPDATE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (24, 'PERM_ACTIVITY_DELETE', 6, 'DELETE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- GL_ACCOUNTS (page 7)
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (25, 'PERM_GL_ACCOUNTS_VIEW',   7, 'VIEW',   'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (26, 'PERM_GL_ACCOUNTS_CREATE', 7, 'CREATE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (27, 'PERM_GL_ACCOUNTS_UPDATE', 7, 'UPDATE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (28, 'PERM_GL_ACCOUNTS_DELETE', 7, 'DELETE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- GL_JOURNALS (page 8)
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (29, 'PERM_GL_JOURNALS_VIEW',   8, 'VIEW',   'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (30, 'PERM_GL_JOURNALS_CREATE', 8, 'CREATE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (31, 'PERM_GL_JOURNALS_UPDATE', 8, 'UPDATE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (32, 'PERM_GL_JOURNALS_DELETE', 8, 'DELETE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- GL_RULES (page 9)
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (33, 'PERM_GL_RULES_VIEW',   9, 'VIEW',   'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (34, 'PERM_GL_RULES_CREATE', 9, 'CREATE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (35, 'PERM_GL_RULES_UPDATE', 9, 'UPDATE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (36, 'PERM_GL_RULES_DELETE', 9, 'DELETE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- GL_POSTINGS (page 10)
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (37, 'PERM_GL_POSTINGS_VIEW',   10, 'VIEW',   'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (38, 'PERM_GL_POSTINGS_CREATE', 10, 'CREATE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (39, 'PERM_GL_POSTINGS_UPDATE', 10, 'UPDATE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO PERMISSIONS (ID, NAME, PAGE_ID_FK, PERMISSION_TYPE, TENANT_ID, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (40, 'PERM_GL_POSTINGS_DELETE', 10, 'DELETE', 'DEFAULT', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- 1.6 Role ↔ Permission assignments
-- مدير النظام (role 1) → ALL permissions
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) SELECT 1, ID FROM PERMISSIONS WHERE TENANT_ID = 'DEFAULT';

-- محاسب (role 2) → GL view/create/update + Dashboard view
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (2,  1); -- DASHBOARD VIEW
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (2, 25); -- GL_ACCOUNTS VIEW
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (2, 26); -- GL_ACCOUNTS CREATE
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (2, 27); -- GL_ACCOUNTS UPDATE
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (2, 29); -- GL_JOURNALS VIEW
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (2, 30); -- GL_JOURNALS CREATE
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (2, 31); -- GL_JOURNALS UPDATE
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (2, 33); -- GL_RULES VIEW
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (2, 37); -- GL_POSTINGS VIEW
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (2, 38); -- GL_POSTINGS CREATE

-- مدير مالي (role 3) → GL full + Dashboard + Lookups view
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (3,  1); -- DASHBOARD VIEW
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (3, 17); -- MASTER_LOOKUP VIEW
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (3, 25); -- GL_ACCOUNTS VIEW
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (3, 26); -- GL_ACCOUNTS CREATE
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (3, 27); -- GL_ACCOUNTS UPDATE
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (3, 28); -- GL_ACCOUNTS DELETE
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (3, 29); -- GL_JOURNALS VIEW
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (3, 30); -- GL_JOURNALS CREATE
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (3, 31); -- GL_JOURNALS UPDATE
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (3, 32); -- GL_JOURNALS DELETE
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (3, 33); -- GL_RULES VIEW
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (3, 34); -- GL_RULES CREATE
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (3, 35); -- GL_RULES UPDATE
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (3, 36); -- GL_RULES DELETE
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (3, 37); -- GL_POSTINGS VIEW
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (3, 38); -- GL_POSTINGS CREATE
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (3, 39); -- GL_POSTINGS UPDATE
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (3, 40); -- GL_POSTINGS DELETE

-- مستخدم عادي (role 4) → view-only on Dashboard, Lookups, GL_ACCOUNTS
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (4,  1); -- DASHBOARD VIEW
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (4, 17); -- MASTER_LOOKUP VIEW
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID) VALUES (4, 25); -- GL_ACCOUNTS VIEW

-- ============================================================
-- 2. MASTER DATA — Lookups
-- ============================================================

-- 2.1 Master Lookup Types
INSERT INTO MD_MASTER_LOOKUP (ID_PK, LOOKUP_KEY, LOOKUP_NAME, LOOKUP_NAME_EN, DESCRIPTION, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_MASTER_LOOKUP_SEQ.NEXTVAL, 'GL_ACCOUNT_TYPE',   'نوع الحساب',       'Account Type',       'أنواع الحسابات في شجرة الحسابات',   1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_MASTER_LOOKUP (ID_PK, LOOKUP_KEY, LOOKUP_NAME, LOOKUP_NAME_EN, DESCRIPTION, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_MASTER_LOOKUP_SEQ.NEXTVAL, 'JOURNAL_TYPE',      'نوع القيد',        'Journal Type',       'أنواع القيود المحاسبية',             1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_MASTER_LOOKUP (ID_PK, LOOKUP_KEY, LOOKUP_NAME, LOOKUP_NAME_EN, DESCRIPTION, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_MASTER_LOOKUP_SEQ.NEXTVAL, 'JOURNAL_STATUS',    'حالة القيد',       'Journal Status',     'حالات القيد المحاسبي',              1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_MASTER_LOOKUP (ID_PK, LOOKUP_KEY, LOOKUP_NAME, LOOKUP_NAME_EN, DESCRIPTION, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_MASTER_LOOKUP_SEQ.NEXTVAL, 'SOURCE_MODULE',     'الوحدة المصدرية',  'Source Module',      'الوحدات المصدرية للترحيلات',         1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_MASTER_LOOKUP (ID_PK, LOOKUP_KEY, LOOKUP_NAME, LOOKUP_NAME_EN, DESCRIPTION, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_MASTER_LOOKUP_SEQ.NEXTVAL, 'ENTRY_SIDE',        'طرف القيد',        'Entry Side',         'طرف القيد المحاسبي (مدين/دائن)',    1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_MASTER_LOOKUP (ID_PK, LOOKUP_KEY, LOOKUP_NAME, LOOKUP_NAME_EN, DESCRIPTION, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_MASTER_LOOKUP_SEQ.NEXTVAL, 'CURRENCY',          'العملات',          'Currency',           'العملات المتاحة في النظام',          1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_MASTER_LOOKUP (ID_PK, LOOKUP_KEY, LOOKUP_NAME, LOOKUP_NAME_EN, DESCRIPTION, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_MASTER_LOOKUP_SEQ.NEXTVAL, 'UOM',               'وحدة القياس',      'Unit of Measure',    'وحدات القياس المستخدمة',             1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_MASTER_LOOKUP (ID_PK, LOOKUP_KEY, LOOKUP_NAME, LOOKUP_NAME_EN, DESCRIPTION, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_MASTER_LOOKUP_SEQ.NEXTVAL, 'PAYMENT_TYPE',      'نوع الدفع',        'Payment Type',       'أنواع طرق الدفع',                    1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_MASTER_LOOKUP (ID_PK, LOOKUP_KEY, LOOKUP_NAME, LOOKUP_NAME_EN, DESCRIPTION, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_MASTER_LOOKUP_SEQ.NEXTVAL, 'POSTING_STATUS',    'حالة الترحيل',     'Posting Status',     'حالات عمليات الترحيل',               1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_MASTER_LOOKUP (ID_PK, LOOKUP_KEY, LOOKUP_NAME, LOOKUP_NAME_EN, DESCRIPTION, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_MASTER_LOOKUP_SEQ.NEXTVAL, 'DOC_TYPE',          'نوع المستند',      'Document Type',      'أنواع المستندات المصدرية',           1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- 2.2 Lookup Details — GL Account Types
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 1, 'ASSETS',       'أصول',          'Assets',              1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 1, 'LIABILITIES',  'خصوم',          'Liabilities',         2, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 1, 'EQUITY',       'حقوق الملكية',  'Equity',              3, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 1, 'REVENUE',      'إيرادات',       'Revenue',             4, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 1, 'EXPENSES',     'مصروفات',       'Expenses',            5, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- Lookup Details — Journal Types
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 2, 'MANUAL',       'يدوي',          'Manual',              1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 2, 'AUTO',         'آلي',           'Automatic',           2, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 2, 'ADJUSTMENT',   'تسوية',         'Adjustment',          3, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 2, 'CLOSING',      'إقفال',         'Closing',             4, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 2, 'REVERSAL',     'عكسي',          'Reversal',            5, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- Lookup Details — Journal Status
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 3, 'DRAFT',        'مسودة',         'Draft',               1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 3, 'SUBMITTED',    'مقدم',          'Submitted',           2, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 3, 'APPROVED',     'معتمد',         'Approved',            3, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 3, 'POSTED',       'مرحّل',         'Posted',              4, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 3, 'REJECTED',     'مرفوض',         'Rejected',            5, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 3, 'CANCELLED',    'ملغي',          'Cancelled',           6, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- Lookup Details — Source Module
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 4, 'GL',           'الأستاذ العام', 'General Ledger',      1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 4, 'BILLING',      'الفواتير',      'Billing',             2, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 4, 'CONTRACT',     'العقود',        'Contracts',           3, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 4, 'HR',           'الموارد البشرية','Human Resources',    4, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- Lookup Details — Entry Side
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 5, 'DEBIT',        'مدين',          'Debit',               1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 5, 'CREDIT',       'دائن',          'Credit',              2, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- Lookup Details — Currency
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, EXTRA_VALUE, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 6, 'EGP', 'جنيه مصري',    'Egyptian Pound',   'EGP', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, EXTRA_VALUE, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 6, 'USD', 'دولار أمريكي', 'US Dollar',        'USD', 2, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, EXTRA_VALUE, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 6, 'SAR', 'ريال سعودي',   'Saudi Riyal',      'SAR', 3, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, EXTRA_VALUE, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 6, 'EUR', 'يورو',         'Euro',             'EUR', 4, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- Lookup Details — UOM
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 7, 'KG',    'كيلوجرام',  'Kilogram',   1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 7, 'TON',   'طن',         'Ton',        2, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 7, 'METER', 'متر',        'Meter',      3, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 7, 'PIECE', 'قطعة',       'Piece',      4, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 7, 'LITER', 'لتر',        'Liter',      5, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- Lookup Details — Payment Type
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 8, 'CASH',           'نقدي',          'Cash',               1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 8, 'BANK_TRANSFER', 'تحويل بنكي',    'Bank Transfer',      2, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 8, 'CHECK',         'شيك',           'Check',              3, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 8, 'CREDIT_CARD',   'بطاقة ائتمان', 'Credit Card',        4, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- Lookup Details — Posting Status
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 9, 'PENDING',       'قيد الانتظار',  'Pending',            1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 9, 'POSTED',        'مرحّل',         'Posted',             2, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 9, 'FAILED',        'فشل',           'Failed',             3, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 9, 'REVERSED',      'معكوس',         'Reversed',           4, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- Lookup Details — Document Type
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 10, 'INVOICE',      'فاتورة',        'Invoice',            1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 10, 'RECEIPT',      'إيصال',         'Receipt',            2, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 10, 'PAYMENT',      'سند صرف',       'Payment Voucher',    3, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_LOOKUP_DETAIL_SEQ.NEXTVAL, 10, 'CREDIT_NOTE',  'إشعار دائن',   'Credit Note',        4, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- ============================================================
-- 2.3 Activities
-- ============================================================
INSERT INTO MD_ACTIVITY (ID_PK, CODE, NAME, DESCRIPTION, DEFAULT_STOCK_UOM_ID_FK, CONVERSION_TYPE, REQUIRES_ACTUAL_WEIGHT, ALLOW_FRACTION, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_ACTIVITY_SEQ.NEXTVAL, 'TRADING',       'تجارة عامة',       'نشاط التجارة والبيع والشراء',       NULL, 'FIXED',    0, 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_ACTIVITY (ID_PK, CODE, NAME, DESCRIPTION, DEFAULT_STOCK_UOM_ID_FK, CONVERSION_TYPE, REQUIRES_ACTUAL_WEIGHT, ALLOW_FRACTION, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_ACTIVITY_SEQ.NEXTVAL, 'MANUFACTURING', 'تصنيع',            'نشاط التصنيع والإنتاج',             NULL, 'VARIABLE', 1, 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_ACTIVITY (ID_PK, CODE, NAME, DESCRIPTION, DEFAULT_STOCK_UOM_ID_FK, CONVERSION_TYPE, REQUIRES_ACTUAL_WEIGHT, ALLOW_FRACTION, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_ACTIVITY_SEQ.NEXTVAL, 'SERVICES',      'خدمات',            'نشاط تقديم الخدمات',                NULL, 'FIXED',    0, 0, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_ACTIVITY (ID_PK, CODE, NAME, DESCRIPTION, DEFAULT_STOCK_UOM_ID_FK, CONVERSION_TYPE, REQUIRES_ACTUAL_WEIGHT, ALLOW_FRACTION, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_ACTIVITY_SEQ.NEXTVAL, 'REAL_ESTATE',   'عقارات',           'نشاط الاستثمار العقاري',            NULL, 'FIXED',    0, 0, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- ============================================================
-- 2.4 Categories
-- ============================================================
INSERT INTO MD_CATEGORY (ID_PK, CODE, NAME, ACTIVITY_ID_FK, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_CATEGORY_SEQ.NEXTVAL, 'ELECTRONICS', 'إلكترونيات',      1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_CATEGORY (ID_PK, CODE, NAME, ACTIVITY_ID_FK, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_CATEGORY_SEQ.NEXTVAL, 'FOOD',        'مواد غذائية',      1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_CATEGORY (ID_PK, CODE, NAME, ACTIVITY_ID_FK, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_CATEGORY_SEQ.NEXTVAL, 'RAW_MATERIAL','مواد خام',         2, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO MD_CATEGORY (ID_PK, CODE, NAME, ACTIVITY_ID_FK, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (MD_CATEGORY_SEQ.NEXTVAL, 'CONSULTING',  'استشارات',         3, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- ============================================================
-- 3. FINANCE — Chart of Accounts (Hierarchical)
-- ============================================================
-- Organization ID = 1 (default company)

-- Level 0: Main Groups
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '1',  'الأصول',          NULL, 'ASSETS',      1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '2',  'الخصوم',          NULL, 'LIABILITIES', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '3',  'حقوق الملكية',   NULL, 'EQUITY',      1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '4',  'الإيرادات',       NULL, 'REVENUE',     1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '5',  'المصروفات',       NULL, 'EXPENSES',    1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- Level 1: Sub-groups under Assets (parent = 1)
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '11', 'أصول متداولة',     1, 'ASSETS', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '12', 'أصول ثابتة',       1, 'ASSETS', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- Level 1: Sub-groups under Liabilities (parent = 2)
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '21', 'خصوم متداولة',     2, 'LIABILITIES', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '22', 'خصوم طويلة الأجل', 2, 'LIABILITIES', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- Level 1: Sub-groups under Revenue (parent = 4)
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '41', 'إيرادات تشغيلية',  4, 'REVENUE', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '42', 'إيرادات أخرى',     4, 'REVENUE', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- Level 1: Sub-groups under Expenses (parent = 5)
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '51', 'مصروفات تشغيلية',  5, 'EXPENSES', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '52', 'مصروفات إدارية',   5, 'EXPENSES', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- Level 2: Leaf accounts (posting accounts)
-- Current Assets (parent = 6 → account "11")
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '1101', 'الصندوق',                   6, 'ASSETS', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '1102', 'البنك - حساب جاري',        6, 'ASSETS', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '1103', 'العملاء (ذمم مدينة)',      6, 'ASSETS', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '1104', 'المخزون',                   6, 'ASSETS', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- Fixed Assets (parent = 7 → account "12")
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '1201', 'الأراضي',                   7, 'ASSETS', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '1202', 'المباني',                   7, 'ASSETS', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '1203', 'الآلات والمعدات',           7, 'ASSETS', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '1204', 'سيارات',                    7, 'ASSETS', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- Current Liabilities (parent = 8 → account "21")
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '2101', 'الموردون (ذمم دائنة)',     8, 'LIABILITIES', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '2102', 'ضريبة القيمة المضافة',     8, 'LIABILITIES', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '2103', 'رواتب مستحقة',             8, 'LIABILITIES', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- Long-term Liabilities (parent = 9 → account "22")
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '2201', 'قروض طويلة الأجل',         9, 'LIABILITIES', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- Equity (parent = 3)
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '31', 'رأس المال',                  3, 'EQUITY', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '32', 'أرباح محتجزة',              3, 'EQUITY', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- Revenue accounts (parent = 10 → "41", 11 → "42")
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '4101', 'إيرادات مبيعات',           10, 'REVENUE', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '4102', 'إيرادات خدمات',            10, 'REVENUE', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '4201', 'إيرادات فوائد',            11, 'REVENUE', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- Expense accounts (parent = 12 → "51", 13 → "52")
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '5101', 'تكلفة البضاعة المباعة',    12, 'EXPENSES', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '5102', 'مصروفات نقل',              12, 'EXPENSES', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '5201', 'رواتب وأجور',              13, 'EXPENSES', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '5202', 'إيجار',                    13, 'EXPENSES', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '5203', 'مصروفات كهرباء ومياه',     13, 'EXPENSES', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO ACCOUNTS_CHART (ACCOUNT_CHART_PK, ACCOUNT_CHART_NO, ACCOUNT_CHART_NAME, ACCOUNT_CHART_FK, ACCOUNT_TYPE, ORGANIZATION_FK, ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACCOUNTS_CHART_SEQ.NEXTVAL, '5204', 'مصروفات اتصالات',          13, 'EXPENSES', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- ============================================================
-- 4. FINANCE — Accounting Rules (Posting Engine)
-- ============================================================
-- Rule: When BILLING module generates INVOICE doc type → create journal entries
INSERT INTO ACC_RULE_HDR (RULE_ID, COMPANY_ID_FK, SOURCE_MODULE, SOURCE_DOC_TYPE, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACC_RULE_HDR_SEQ.NEXTVAL, 1, 'BILLING', 'INVOICE', 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- Rule line 1: Debit Accounts Receivable (account 1103 = pk 16)
INSERT INTO ACC_RULE_LINE (RULE_LINE_ID, RULE_ID_FK, BUSINESS_SIDE, ACCOUNT_ID_FK, ENTRY_SIDE, PRIORITY, AMOUNT_SOURCE_TYPE, AMOUNT_SOURCE_VALUE, PAYMENT_TYPE_CODE, ENTITY_TYPE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACC_RULE_LINE_SEQ.NEXTVAL, 1, 'RECEIVABLE', 16, 'DEBIT', 1, 'FULL_AMOUNT', NULL, NULL, 'CUSTOMER', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- Rule line 2: Credit Revenue (account 4101 = pk 29)
INSERT INTO ACC_RULE_LINE (RULE_LINE_ID, RULE_ID_FK, BUSINESS_SIDE, ACCOUNT_ID_FK, ENTRY_SIDE, PRIORITY, AMOUNT_SOURCE_TYPE, AMOUNT_SOURCE_VALUE, PAYMENT_TYPE_CODE, ENTITY_TYPE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACC_RULE_LINE_SEQ.NEXTVAL, 1, 'REVENUE', 28, 'CREDIT', 2, 'FULL_AMOUNT', NULL, NULL, NULL, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- Rule: BILLING + RECEIPT (cash receipt from customer)
INSERT INTO ACC_RULE_HDR (RULE_ID, COMPANY_ID_FK, SOURCE_MODULE, SOURCE_DOC_TYPE, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACC_RULE_HDR_SEQ.NEXTVAL, 1, 'BILLING', 'RECEIPT', 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- Debit Cash (1101 = pk 14)
INSERT INTO ACC_RULE_LINE (RULE_LINE_ID, RULE_ID_FK, BUSINESS_SIDE, ACCOUNT_ID_FK, ENTRY_SIDE, PRIORITY, AMOUNT_SOURCE_TYPE, AMOUNT_SOURCE_VALUE, PAYMENT_TYPE_CODE, ENTITY_TYPE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACC_RULE_LINE_SEQ.NEXTVAL, 2, 'CASH', 14, 'DEBIT', 1, 'FULL_AMOUNT', NULL, 'CASH', NULL, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- Credit Accounts Receivable (1103 = pk 16)
INSERT INTO ACC_RULE_LINE (RULE_LINE_ID, RULE_ID_FK, BUSINESS_SIDE, ACCOUNT_ID_FK, ENTRY_SIDE, PRIORITY, AMOUNT_SOURCE_TYPE, AMOUNT_SOURCE_VALUE, PAYMENT_TYPE_CODE, ENTITY_TYPE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACC_RULE_LINE_SEQ.NEXTVAL, 2, 'RECEIVABLE', 16, 'CREDIT', 2, 'FULL_AMOUNT', NULL, NULL, 'CUSTOMER', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- ============================================================
-- 5. FINANCE — Sample Journal Entries
-- ============================================================

-- Journal 1: فاتورة مبيعات عميل (Sales Invoice)
INSERT INTO GL_JOURNAL_HDR (ID_PK, JOURNAL_NO, JOURNAL_DATE, JOURNAL_TYPE_ID_FK, STATUS_ID_FK, DESCRIPTION, SOURCE_MODULE_ID_FK, TOTAL_DEBIT, TOTAL_CREDIT, ACTIVE_FL, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_JOURNAL_HDR_SEQ.NEXTVAL, 'JV-2026-0001', DATE '2026-01-15', 'MANUAL', 'POSTED', 'فاتورة مبيعات - العميل أحمد للتجارة', 'GL', 150000.00, 150000.00, 1, SYSTIMESTAMP, 'admin', SYSTIMESTAMP, 'admin');

INSERT INTO GL_JOURNAL_LINE (ID_PK, JOURNAL_ID_FK, LINE_NO, ACCOUNT_ID_FK, DEBIT_AMOUNT, CREDIT_AMOUNT, DESCRIPTION, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_JOURNAL_LINE_SEQ.NEXTVAL, 1, 1, 16, 150000.00, NULL, 'ذمم مدينة - أحمد للتجارة', SYSTIMESTAMP, 'admin', SYSTIMESTAMP, 'admin');
INSERT INTO GL_JOURNAL_LINE (ID_PK, JOURNAL_ID_FK, LINE_NO, ACCOUNT_ID_FK, DEBIT_AMOUNT, CREDIT_AMOUNT, DESCRIPTION, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_JOURNAL_LINE_SEQ.NEXTVAL, 1, 2, 28, NULL, 150000.00, 'إيرادات مبيعات', SYSTIMESTAMP, 'admin', SYSTIMESTAMP, 'admin');

-- Journal 2: سداد مصروفات إيجار (Rent Payment)
INSERT INTO GL_JOURNAL_HDR (ID_PK, JOURNAL_NO, JOURNAL_DATE, JOURNAL_TYPE_ID_FK, STATUS_ID_FK, DESCRIPTION, SOURCE_MODULE_ID_FK, TOTAL_DEBIT, TOTAL_CREDIT, ACTIVE_FL, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_JOURNAL_HDR_SEQ.NEXTVAL, 'JV-2026-0002', DATE '2026-01-20', 'MANUAL', 'POSTED', 'سداد إيجار شهر يناير 2026', 'GL', 25000.00, 25000.00, 1, SYSTIMESTAMP, 'ahmed.mahmoud', SYSTIMESTAMP, 'ahmed.mahmoud');

INSERT INTO GL_JOURNAL_LINE (ID_PK, JOURNAL_ID_FK, LINE_NO, ACCOUNT_ID_FK, DEBIT_AMOUNT, CREDIT_AMOUNT, DESCRIPTION, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_JOURNAL_LINE_SEQ.NEXTVAL, 2, 1, 34, 25000.00, NULL, 'مصروف إيجار يناير', SYSTIMESTAMP, 'ahmed.mahmoud', SYSTIMESTAMP, 'ahmed.mahmoud');
INSERT INTO GL_JOURNAL_LINE (ID_PK, JOURNAL_ID_FK, LINE_NO, ACCOUNT_ID_FK, DEBIT_AMOUNT, CREDIT_AMOUNT, DESCRIPTION, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_JOURNAL_LINE_SEQ.NEXTVAL, 2, 2, 15, NULL, 25000.00, 'سداد من البنك', SYSTIMESTAMP, 'ahmed.mahmoud', SYSTIMESTAMP, 'ahmed.mahmoud');

-- Journal 3: شراء بضاعة من مورد (Purchase from Supplier)
INSERT INTO GL_JOURNAL_HDR (ID_PK, JOURNAL_NO, JOURNAL_DATE, JOURNAL_TYPE_ID_FK, STATUS_ID_FK, DESCRIPTION, SOURCE_MODULE_ID_FK, TOTAL_DEBIT, TOTAL_CREDIT, ACTIVE_FL, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_JOURNAL_HDR_SEQ.NEXTVAL, 'JV-2026-0003', DATE '2026-02-01', 'MANUAL', 'APPROVED', 'شراء بضاعة من مورد النسيج', 'GL', 85000.00, 85000.00, 1, SYSTIMESTAMP, 'sara.ali', SYSTIMESTAMP, 'sara.ali');

INSERT INTO GL_JOURNAL_LINE (ID_PK, JOURNAL_ID_FK, LINE_NO, ACCOUNT_ID_FK, DEBIT_AMOUNT, CREDIT_AMOUNT, DESCRIPTION, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_JOURNAL_LINE_SEQ.NEXTVAL, 3, 1, 17, 85000.00, NULL, 'بضاعة مشتراة', SYSTIMESTAMP, 'sara.ali', SYSTIMESTAMP, 'sara.ali');
INSERT INTO GL_JOURNAL_LINE (ID_PK, JOURNAL_ID_FK, LINE_NO, ACCOUNT_ID_FK, DEBIT_AMOUNT, CREDIT_AMOUNT, DESCRIPTION, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_JOURNAL_LINE_SEQ.NEXTVAL, 3, 2, 22, NULL, 85000.00, 'ذمم دائنة - مورد النسيج', SYSTIMESTAMP, 'sara.ali', SYSTIMESTAMP, 'sara.ali');

-- Journal 4: صرف رواتب شهر يناير (Salary Payment)
INSERT INTO GL_JOURNAL_HDR (ID_PK, JOURNAL_NO, JOURNAL_DATE, JOURNAL_TYPE_ID_FK, STATUS_ID_FK, DESCRIPTION, SOURCE_MODULE_ID_FK, TOTAL_DEBIT, TOTAL_CREDIT, ACTIVE_FL, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_JOURNAL_HDR_SEQ.NEXTVAL, 'JV-2026-0004', DATE '2026-01-31', 'MANUAL', 'POSTED', 'صرف رواتب شهر يناير 2026', 'HR', 120000.00, 120000.00, 1, SYSTIMESTAMP, 'sara.ali', SYSTIMESTAMP, 'sara.ali');

INSERT INTO GL_JOURNAL_LINE (ID_PK, JOURNAL_ID_FK, LINE_NO, ACCOUNT_ID_FK, DEBIT_AMOUNT, CREDIT_AMOUNT, DESCRIPTION, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_JOURNAL_LINE_SEQ.NEXTVAL, 4, 1, 33, 120000.00, NULL, 'مصروف رواتب يناير', SYSTIMESTAMP, 'sara.ali', SYSTIMESTAMP, 'sara.ali');
INSERT INTO GL_JOURNAL_LINE (ID_PK, JOURNAL_ID_FK, LINE_NO, ACCOUNT_ID_FK, DEBIT_AMOUNT, CREDIT_AMOUNT, DESCRIPTION, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_JOURNAL_LINE_SEQ.NEXTVAL, 4, 2, 15, NULL, 120000.00, 'سداد من البنك', SYSTIMESTAMP, 'sara.ali', SYSTIMESTAMP, 'sara.ali');

-- Journal 5: تحصيل من عميل (Customer Payment Received)
INSERT INTO GL_JOURNAL_HDR (ID_PK, JOURNAL_NO, JOURNAL_DATE, JOURNAL_TYPE_ID_FK, STATUS_ID_FK, DESCRIPTION, SOURCE_MODULE_ID_FK, TOTAL_DEBIT, TOTAL_CREDIT, ACTIVE_FL, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_JOURNAL_HDR_SEQ.NEXTVAL, 'JV-2026-0005', DATE '2026-02-10', 'MANUAL', 'DRAFT', 'تحصيل جزئي من عميل أحمد للتجارة', 'GL', 75000.00, 75000.00, 1, SYSTIMESTAMP, 'ahmed.mahmoud', SYSTIMESTAMP, 'ahmed.mahmoud');

INSERT INTO GL_JOURNAL_LINE (ID_PK, JOURNAL_ID_FK, LINE_NO, ACCOUNT_ID_FK, DEBIT_AMOUNT, CREDIT_AMOUNT, DESCRIPTION, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_JOURNAL_LINE_SEQ.NEXTVAL, 5, 1, 14, 75000.00, NULL, 'تحصيل نقدي من العميل', SYSTIMESTAMP, 'ahmed.mahmoud', SYSTIMESTAMP, 'ahmed.mahmoud');
INSERT INTO GL_JOURNAL_LINE (ID_PK, JOURNAL_ID_FK, LINE_NO, ACCOUNT_ID_FK, DEBIT_AMOUNT, CREDIT_AMOUNT, DESCRIPTION, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_JOURNAL_LINE_SEQ.NEXTVAL, 5, 2, 16, NULL, 75000.00, 'تخفيض ذمم مدينة', SYSTIMESTAMP, 'ahmed.mahmoud', SYSTIMESTAMP, 'ahmed.mahmoud');

-- Journal 6: مصروف كهرباء ومياه (Utilities Expense)
INSERT INTO GL_JOURNAL_HDR (ID_PK, JOURNAL_NO, JOURNAL_DATE, JOURNAL_TYPE_ID_FK, STATUS_ID_FK, DESCRIPTION, SOURCE_MODULE_ID_FK, TOTAL_DEBIT, TOTAL_CREDIT, ACTIVE_FL, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_JOURNAL_HDR_SEQ.NEXTVAL, 'JV-2026-0006', DATE '2026-02-15', 'MANUAL', 'SUBMITTED', 'فاتورة كهرباء ومياه شهر يناير', 'GL', 8500.00, 8500.00, 1, SYSTIMESTAMP, 'ahmed.mahmoud', SYSTIMESTAMP, 'ahmed.mahmoud');

INSERT INTO GL_JOURNAL_LINE (ID_PK, JOURNAL_ID_FK, LINE_NO, ACCOUNT_ID_FK, DEBIT_AMOUNT, CREDIT_AMOUNT, DESCRIPTION, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_JOURNAL_LINE_SEQ.NEXTVAL, 6, 1, 35, 8500.00, NULL, 'مصروف كهرباء ومياه', SYSTIMESTAMP, 'ahmed.mahmoud', SYSTIMESTAMP, 'ahmed.mahmoud');
INSERT INTO GL_JOURNAL_LINE (ID_PK, JOURNAL_ID_FK, LINE_NO, ACCOUNT_ID_FK, DEBIT_AMOUNT, CREDIT_AMOUNT, DESCRIPTION, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_JOURNAL_LINE_SEQ.NEXTVAL, 6, 2, 14, NULL, 8500.00, 'سداد نقدي', SYSTIMESTAMP, 'ahmed.mahmoud', SYSTIMESTAMP, 'ahmed.mahmoud');

-- ============================================================
-- 6. FINANCE — Sample Posting (linked to Journal 1)
-- ============================================================

INSERT INTO ACC_POSTING_MST (POSTING_ID, COMPANY_ID_FK, DOC_DATE, SOURCE_DOC_ID, SOURCE_DOC_NO, SOURCE_DOC_TYPE, SOURCE_MODULE, STATUS, TOTAL_AMOUNT, CURRENCY_CODE, FIN_JOURNAL_ID_FK, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACC_POSTING_MST_SEQ.NEXTVAL, 1, DATE '2026-01-15', 1001, 'INV-2026-0001', 'INVOICE', 'BILLING', 'POSTED', 150000.00, 'EGP', 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

INSERT INTO ACC_POSTING_DTL (POSTING_DTL_ID, POSTING_ID_FK, LINE_NO, AMOUNT, BUSINESS_SIDE, SIGN, DESCRIPTION, CUSTOMER_ID_FK, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACC_POSTING_DTL_SEQ.NEXTVAL, 1, 1, 150000.00, 'REVENUE', 1, 'إيراد مبيعات فاتورة INV-2026-0001', 101, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

INSERT INTO ACC_POSTING_MST (POSTING_ID, COMPANY_ID_FK, DOC_DATE, SOURCE_DOC_ID, SOURCE_DOC_NO, SOURCE_DOC_TYPE, SOURCE_MODULE, STATUS, TOTAL_AMOUNT, CURRENCY_CODE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACC_POSTING_MST_SEQ.NEXTVAL, 1, DATE '2026-02-01', 2001, 'PO-2026-0001', 'INVOICE', 'BILLING', 'DRAFT', 85000.00, 'EGP', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

INSERT INTO ACC_POSTING_DTL (POSTING_DTL_ID, POSTING_ID_FK, LINE_NO, AMOUNT, BUSINESS_SIDE, SIGN, DESCRIPTION, SUPPLIER_ID_FK, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (ACC_POSTING_DTL_SEQ.NEXTVAL, 2, 1, 85000.00, 'EXPENSE', -1, 'مشتريات من مورد النسيج', 201, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- ============================================================
-- 7. FINANCE — Fiscal Periods (2026, company 1)
-- ============================================================
INSERT INTO GL_FISCAL_PERIOD (ID_PK, COMPANY_ID_FK, FISCAL_YEAR, PERIOD_NO, PERIOD_NAME, START_DATE, END_DATE, STATUS, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_FISCAL_PERIOD_SEQ.NEXTVAL, 1, 2026,  1, 'يناير 2026',   DATE '2026-01-01', DATE '2026-01-31', 'OPEN', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO GL_FISCAL_PERIOD (ID_PK, COMPANY_ID_FK, FISCAL_YEAR, PERIOD_NO, PERIOD_NAME, START_DATE, END_DATE, STATUS, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_FISCAL_PERIOD_SEQ.NEXTVAL, 1, 2026,  2, 'فبراير 2026',  DATE '2026-02-01', DATE '2026-02-28', 'OPEN', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO GL_FISCAL_PERIOD (ID_PK, COMPANY_ID_FK, FISCAL_YEAR, PERIOD_NO, PERIOD_NAME, START_DATE, END_DATE, STATUS, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_FISCAL_PERIOD_SEQ.NEXTVAL, 1, 2026,  3, 'مارس 2026',    DATE '2026-03-01', DATE '2026-03-31', 'OPEN', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO GL_FISCAL_PERIOD (ID_PK, COMPANY_ID_FK, FISCAL_YEAR, PERIOD_NO, PERIOD_NAME, START_DATE, END_DATE, STATUS, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_FISCAL_PERIOD_SEQ.NEXTVAL, 1, 2026,  4, 'أبريل 2026',   DATE '2026-04-01', DATE '2026-04-30', 'OPEN', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO GL_FISCAL_PERIOD (ID_PK, COMPANY_ID_FK, FISCAL_YEAR, PERIOD_NO, PERIOD_NAME, START_DATE, END_DATE, STATUS, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_FISCAL_PERIOD_SEQ.NEXTVAL, 1, 2026,  5, 'مايو 2026',    DATE '2026-05-01', DATE '2026-05-31', 'OPEN', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO GL_FISCAL_PERIOD (ID_PK, COMPANY_ID_FK, FISCAL_YEAR, PERIOD_NO, PERIOD_NAME, START_DATE, END_DATE, STATUS, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_FISCAL_PERIOD_SEQ.NEXTVAL, 1, 2026,  6, 'يونيو 2026',   DATE '2026-06-01', DATE '2026-06-30', 'OPEN', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO GL_FISCAL_PERIOD (ID_PK, COMPANY_ID_FK, FISCAL_YEAR, PERIOD_NO, PERIOD_NAME, START_DATE, END_DATE, STATUS, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_FISCAL_PERIOD_SEQ.NEXTVAL, 1, 2026,  7, 'يوليو 2026',   DATE '2026-07-01', DATE '2026-07-31', 'OPEN', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO GL_FISCAL_PERIOD (ID_PK, COMPANY_ID_FK, FISCAL_YEAR, PERIOD_NO, PERIOD_NAME, START_DATE, END_DATE, STATUS, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_FISCAL_PERIOD_SEQ.NEXTVAL, 1, 2026,  8, 'أغسطس 2026',   DATE '2026-08-01', DATE '2026-08-31', 'OPEN', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO GL_FISCAL_PERIOD (ID_PK, COMPANY_ID_FK, FISCAL_YEAR, PERIOD_NO, PERIOD_NAME, START_DATE, END_DATE, STATUS, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_FISCAL_PERIOD_SEQ.NEXTVAL, 1, 2026,  9, 'سبتمبر 2026',  DATE '2026-09-01', DATE '2026-09-30', 'OPEN', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO GL_FISCAL_PERIOD (ID_PK, COMPANY_ID_FK, FISCAL_YEAR, PERIOD_NO, PERIOD_NAME, START_DATE, END_DATE, STATUS, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_FISCAL_PERIOD_SEQ.NEXTVAL, 1, 2026, 10, 'أكتوبر 2026',  DATE '2026-10-01', DATE '2026-10-31', 'OPEN', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO GL_FISCAL_PERIOD (ID_PK, COMPANY_ID_FK, FISCAL_YEAR, PERIOD_NO, PERIOD_NAME, START_DATE, END_DATE, STATUS, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_FISCAL_PERIOD_SEQ.NEXTVAL, 1, 2026, 11, 'نوفمبر 2026',  DATE '2026-11-01', DATE '2026-11-30', 'OPEN', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');
INSERT INTO GL_FISCAL_PERIOD (ID_PK, COMPANY_ID_FK, FISCAL_YEAR, PERIOD_NO, PERIOD_NAME, START_DATE, END_DATE, STATUS, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (GL_FISCAL_PERIOD_SEQ.NEXTVAL, 1, 2026, 12, 'ديسمبر 2026',  DATE '2026-12-01', DATE '2026-12-31', 'OPEN', SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM');

-- ============================================================
-- 8. FINANCE — Document Counters (2026, company 1)
-- ============================================================
INSERT INTO GL_DOCUMENT_COUNTER (COMPANY_ID, DOC_TYPE, FISCAL_YEAR, PERIOD_NO, CURRENT_VALUE, UPDATED_AT) VALUES (1, 'JOURNAL',  2026, 1, 6, SYSTIMESTAMP);
INSERT INTO GL_DOCUMENT_COUNTER (COMPANY_ID, DOC_TYPE, FISCAL_YEAR, PERIOD_NO, CURRENT_VALUE, UPDATED_AT) VALUES (1, 'JOURNAL',  2026, 2, 0, SYSTIMESTAMP);
INSERT INTO GL_DOCUMENT_COUNTER (COMPANY_ID, DOC_TYPE, FISCAL_YEAR, PERIOD_NO, CURRENT_VALUE, UPDATED_AT) VALUES (1, 'INVOICE',  2026, 1, 1, SYSTIMESTAMP);

-- ============================================================
-- 9. SECURITY — Menu Items (sidebar navigation)
-- ============================================================
-- Top-level menu groups
INSERT INTO SEC_MENU_ITEM (ID, NAME_AR, NAME_EN, ROUTE_PATH, PARENT_ID, PERM_CODE, DISPLAY_ORDER, ICON, IS_ACTIVE, TENANT_ID)
VALUES (SEC_MENU_ITEM_SEQ.NEXTVAL, 'لوحة التحكم',       'Dashboard',         '/dashboard',              NULL, 'PERM_DASHBOARD_VIEW',         1,  'feather:home',         1, 'DEFAULT');
INSERT INTO SEC_MENU_ITEM (ID, NAME_AR, NAME_EN, ROUTE_PATH, PARENT_ID, PERM_CODE, DISPLAY_ORDER, ICON, IS_ACTIVE, TENANT_ID)
VALUES (SEC_MENU_ITEM_SEQ.NEXTVAL, 'الأمان',             'Security',          NULL,                      NULL, NULL,                          2,  'feather:shield',       1, 'DEFAULT');
INSERT INTO SEC_MENU_ITEM (ID, NAME_AR, NAME_EN, ROUTE_PATH, PARENT_ID, PERM_CODE, DISPLAY_ORDER, ICON, IS_ACTIVE, TENANT_ID)
VALUES (SEC_MENU_ITEM_SEQ.NEXTVAL, 'البيانات الأساسية',  'Master Data',       NULL,                      NULL, NULL,                          3,  'feather:database',     1, 'DEFAULT');
INSERT INTO SEC_MENU_ITEM (ID, NAME_AR, NAME_EN, ROUTE_PATH, PARENT_ID, PERM_CODE, DISPLAY_ORDER, ICON, IS_ACTIVE, TENANT_ID)
VALUES (SEC_MENU_ITEM_SEQ.NEXTVAL, 'المالية',            'Finance',           NULL,                      NULL, NULL,                          4,  'feather:dollar-sign',  1, 'DEFAULT');

-- Security sub-items (parent = 2)
INSERT INTO SEC_MENU_ITEM (ID, NAME_AR, NAME_EN, ROUTE_PATH, PARENT_ID, PERM_CODE, DISPLAY_ORDER, ICON, IS_ACTIVE, TENANT_ID)
VALUES (SEC_MENU_ITEM_SEQ.NEXTVAL, 'إدارة المستخدمين',  'User Management',   '/security/users',         2, 'PERM_USER_MANAGEMENT_VIEW',    1,  'feather:users',        1, 'DEFAULT');
INSERT INTO SEC_MENU_ITEM (ID, NAME_AR, NAME_EN, ROUTE_PATH, PARENT_ID, PERM_CODE, DISPLAY_ORDER, ICON, IS_ACTIVE, TENANT_ID)
VALUES (SEC_MENU_ITEM_SEQ.NEXTVAL, 'إدارة الصلاحيات',   'Role Access',       '/security/roles',         2, 'PERM_ROLE_ACCESS_VIEW',        2,  'feather:lock',         1, 'DEFAULT');
INSERT INTO SEC_MENU_ITEM (ID, NAME_AR, NAME_EN, ROUTE_PATH, PARENT_ID, PERM_CODE, DISPLAY_ORDER, ICON, IS_ACTIVE, TENANT_ID)
VALUES (SEC_MENU_ITEM_SEQ.NEXTVAL, 'سجل الصفحات',       'Pages Registry',    '/security/pages',         2, 'PERM_PAGES_REGISTRY_VIEW',     3,  'feather:layout',       1, 'DEFAULT');

-- Master Data sub-items (parent = 3)
INSERT INTO SEC_MENU_ITEM (ID, NAME_AR, NAME_EN, ROUTE_PATH, PARENT_ID, PERM_CODE, DISPLAY_ORDER, ICON, IS_ACTIVE, TENANT_ID)
VALUES (SEC_MENU_ITEM_SEQ.NEXTVAL, 'القوائم المرجعية',  'Master Lookups',    '/masterdata/lookups',     3, 'PERM_MASTER_LOOKUP_VIEW',      1,  'feather:list',         1, 'DEFAULT');
INSERT INTO SEC_MENU_ITEM (ID, NAME_AR, NAME_EN, ROUTE_PATH, PARENT_ID, PERM_CODE, DISPLAY_ORDER, ICON, IS_ACTIVE, TENANT_ID)
VALUES (SEC_MENU_ITEM_SEQ.NEXTVAL, 'الأنشطة',           'Activities',        '/masterdata/activities',  3, 'PERM_ACTIVITY_VIEW',           2,  'feather:activity',     1, 'DEFAULT');

-- Finance sub-items (parent = 4)
INSERT INTO SEC_MENU_ITEM (ID, NAME_AR, NAME_EN, ROUTE_PATH, PARENT_ID, PERM_CODE, DISPLAY_ORDER, ICON, IS_ACTIVE, TENANT_ID)
VALUES (SEC_MENU_ITEM_SEQ.NEXTVAL, 'شجرة الحسابات',     'Chart of Accounts', '/finance/gl/accounts',    4, 'PERM_GL_ACCOUNTS_VIEW',        1,  'feather:git-branch',   1, 'DEFAULT');
INSERT INTO SEC_MENU_ITEM (ID, NAME_AR, NAME_EN, ROUTE_PATH, PARENT_ID, PERM_CODE, DISPLAY_ORDER, ICON, IS_ACTIVE, TENANT_ID)
VALUES (SEC_MENU_ITEM_SEQ.NEXTVAL, 'القيود اليومية',    'Journal Entries',   '/finance/gl/journals',    4, 'PERM_GL_JOURNALS_VIEW',        2,  'feather:book-open',    1, 'DEFAULT');
INSERT INTO SEC_MENU_ITEM (ID, NAME_AR, NAME_EN, ROUTE_PATH, PARENT_ID, PERM_CODE, DISPLAY_ORDER, ICON, IS_ACTIVE, TENANT_ID)
VALUES (SEC_MENU_ITEM_SEQ.NEXTVAL, 'قواعد الترحيل',     'Posting Rules',     '/finance/gl/rules',       4, 'PERM_GL_RULES_VIEW',           3,  'feather:settings',     1, 'DEFAULT');
INSERT INTO SEC_MENU_ITEM (ID, NAME_AR, NAME_EN, ROUTE_PATH, PARENT_ID, PERM_CODE, DISPLAY_ORDER, ICON, IS_ACTIVE, TENANT_ID)
VALUES (SEC_MENU_ITEM_SEQ.NEXTVAL, 'الترحيلات',         'Postings',          '/finance/gl/postings',    4, 'PERM_GL_POSTINGS_VIEW',        4,  'feather:send',         1, 'DEFAULT');

-- ============================================================
-- COMMIT
-- ============================================================
COMMIT;
