-- ============================================================
-- V10: GL Posting — SEC_PAGES entry + fix permission PAGE_ID_FK
-- ============================================================

-- ── 1. Insert GL_POSTING page (child of GL parent, order 4) ─

MERGE INTO SEC_PAGES tgt
USING (SELECT 'default' AS TENANT_ID, 'GL_POSTING' AS PAGE_CODE FROM DUAL) src
  ON (tgt.TENANT_ID = src.TENANT_ID AND tgt.PAGE_CODE = src.PAGE_CODE)
WHEN NOT MATCHED THEN INSERT
  (ID_PK, TENANT_ID, PAGE_CODE, NAME_AR, NAME_EN, ROUTE, ICON, MODULE, PARENT_ID_FK, DISPLAY_ORDER, IS_ACTIVE, DESCRIPTION, CREATED_AT, CREATED_BY)
  VALUES (SEC_PAGES_SEQ.NEXTVAL, 'default', 'GL_POSTING', N'قيود الترحيل', 'GL Postings', '/finance/gl/postings', 'ti ti-file-export', 'FINANCE',
          (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL' AND TENANT_ID = 'default'), 4, 1, 'GL Postings management page', SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET
  tgt.NAME_AR = N'قيود الترحيل', tgt.NAME_EN = 'GL Postings',
  tgt.ROUTE = '/finance/gl/postings', tgt.ICON = 'ti ti-file-export', tgt.MODULE = 'FINANCE',
  tgt.PARENT_ID_FK = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL' AND TENANT_ID = 'default'),
  tgt.IS_ACTIVE = 1, tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';

-- ── 2. Re-point existing posting permissions to GL_POSTING page ─

UPDATE PERMISSIONS
   SET PAGE_ID_FK  = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_POSTING' AND TENANT_ID = 'default'),
       UPDATED_AT  = SYSTIMESTAMP,
       UPDATED_BY  = 'SYSTEM'
 WHERE NAME IN ('PERM_GL_POSTING_VIEW', 'PERM_GL_POSTING_GENERATE_JOURNAL', 'PERM_GL_POSTING_EXECUTE');

-- ── 3. Add standard CRUD permissions for GL_POSTING page ────

MERGE INTO PERMISSIONS tgt
USING (SELECT 'PERM_GL_POSTING_CREATE' AS NAME FROM DUAL) src
  ON (tgt.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, TENANT_ID, PAGE_ID_FK, PERMISSION_TYPE, CREATED_AT, CREATED_BY)
  VALUES ('PERM_GL_POSTING_CREATE', 'default',
          (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_POSTING' AND TENANT_ID = 'default'),
          'CREATE', SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET
  tgt.TENANT_ID = 'default',
  tgt.PAGE_ID_FK = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_POSTING' AND TENANT_ID = 'default'),
  tgt.PERMISSION_TYPE = 'CREATE',
  tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';

MERGE INTO PERMISSIONS tgt
USING (SELECT 'PERM_GL_POSTING_UPDATE' AS NAME FROM DUAL) src
  ON (tgt.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, TENANT_ID, PAGE_ID_FK, PERMISSION_TYPE, CREATED_AT, CREATED_BY)
  VALUES ('PERM_GL_POSTING_UPDATE', 'default',
          (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_POSTING' AND TENANT_ID = 'default'),
          'UPDATE', SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET
  tgt.TENANT_ID = 'default',
  tgt.PAGE_ID_FK = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_POSTING' AND TENANT_ID = 'default'),
  tgt.PERMISSION_TYPE = 'UPDATE',
  tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';

MERGE INTO PERMISSIONS tgt
USING (SELECT 'PERM_GL_POSTING_DELETE' AS NAME FROM DUAL) src
  ON (tgt.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, TENANT_ID, PAGE_ID_FK, PERMISSION_TYPE, CREATED_AT, CREATED_BY)
  VALUES ('PERM_GL_POSTING_DELETE', 'default',
          (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_POSTING' AND TENANT_ID = 'default'),
          'DELETE', SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET
  tgt.TENANT_ID = 'default',
  tgt.PAGE_ID_FK = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_POSTING' AND TENANT_ID = 'default'),
  tgt.PERMISSION_TYPE = 'DELETE',
  tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';

-- ── 4. Update PERM_GL_POSTING_VIEW to have proper PERMISSION_TYPE ─

UPDATE PERMISSIONS
   SET PERMISSION_TYPE = 'VIEW',
       UPDATED_AT      = SYSTIMESTAMP,
       UPDATED_BY      = 'SYSTEM'
 WHERE NAME = 'PERM_GL_POSTING_VIEW'
   AND (PERMISSION_TYPE IS NULL OR PERMISSION_TYPE <> 'VIEW');
