-- ============================================================
-- V11: Consolidate GL Posting Permissions
--   - Remove PERM_GL_POSTING_GENERATE_JOURNAL  (use PERM_GL_POSTING_CREATE)
--   - Remove PERM_GL_POSTING_EXECUTE           (use PERM_GL_POSTING_UPDATE)
--   - Reassign role mappings before deletion
-- ============================================================

-- ── 1. Migrate ROLE_PERMISSIONS from GENERATE_JOURNAL → CREATE ──

INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID)
SELECT rp.ROLE_ID,
       (SELECT ID FROM PERMISSIONS WHERE NAME = 'PERM_GL_POSTING_CREATE')
  FROM ROLE_PERMISSIONS rp
  JOIN PERMISSIONS p ON p.ID = rp.PERM_ID
 WHERE p.NAME = 'PERM_GL_POSTING_GENERATE_JOURNAL'
   AND NOT EXISTS (
       SELECT 1 FROM ROLE_PERMISSIONS rp2
        WHERE rp2.ROLE_ID = rp.ROLE_ID
          AND rp2.PERM_ID = (SELECT ID FROM PERMISSIONS WHERE NAME = 'PERM_GL_POSTING_CREATE')
   );

-- ── 2. Migrate ROLE_PERMISSIONS from EXECUTE → UPDATE ──

INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERM_ID)
SELECT rp.ROLE_ID,
       (SELECT ID FROM PERMISSIONS WHERE NAME = 'PERM_GL_POSTING_UPDATE')
  FROM ROLE_PERMISSIONS rp
  JOIN PERMISSIONS p ON p.ID = rp.PERM_ID
 WHERE p.NAME = 'PERM_GL_POSTING_EXECUTE'
   AND NOT EXISTS (
       SELECT 1 FROM ROLE_PERMISSIONS rp2
        WHERE rp2.ROLE_ID = rp.ROLE_ID
          AND rp2.PERM_ID = (SELECT ID FROM PERMISSIONS WHERE NAME = 'PERM_GL_POSTING_UPDATE')
   );

-- ── 3. Delete old role mappings ──

DELETE FROM ROLE_PERMISSIONS
 WHERE PERM_ID IN (
   SELECT ID FROM PERMISSIONS
    WHERE NAME IN ('PERM_GL_POSTING_GENERATE_JOURNAL', 'PERM_GL_POSTING_EXECUTE')
 );

-- ── 4. Delete obsolete permissions ──

DELETE FROM PERMISSIONS WHERE NAME = 'PERM_GL_POSTING_GENERATE_JOURNAL';
DELETE FROM PERMISSIONS WHERE NAME = 'PERM_GL_POSTING_EXECUTE';

COMMIT;
