-- ============================================================
-- V7: GL Journal Header & Lines
-- ============================================================

-- ── Drop existing objects (if re-running) ───────────────────
DROP TABLE GL_JOURNAL_LINE CASCADE CONSTRAINTS;
DROP TABLE GL_JOURNAL_HDR CASCADE CONSTRAINTS;
DROP SEQUENCE GL_JOURNAL_HDR_SEQ;
DROP SEQUENCE GL_JOURNAL_LINE_SEQ;
DROP SEQUENCE GL_JOURNAL_NO_SEQ;

-- Sequences
CREATE SEQUENCE GL_JOURNAL_HDR_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE GL_JOURNAL_LINE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE GL_JOURNAL_NO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- ── GL_JOURNAL_HDR ──────────────────────────────────────────
CREATE TABLE GL_JOURNAL_HDR (
    ID_PK                 NUMBER            NOT NULL,
    JOURNAL_NO            VARCHAR2(50)      NOT NULL,
    JOURNAL_DATE          DATE              NOT NULL,
    JOURNAL_TYPE_ID_FK    VARCHAR2(50)      NOT NULL,
    STATUS_ID_FK          VARCHAR2(50)      NOT NULL,
    DESCRIPTION           VARCHAR2(500),
    SOURCE_MODULE_ID_FK   VARCHAR2(50),
    SOURCE_DOC_TYPE_ID    VARCHAR2(50),
    SOURCE_DOC_ID_FK      NUMBER,
    SOURCE_POSTING_ID_FK  NUMBER,
    TOTAL_DEBIT           NUMBER(18,2)      DEFAULT 0 NOT NULL,
    TOTAL_CREDIT          NUMBER(18,2)      DEFAULT 0 NOT NULL,
    ACTIVE_FL             NUMBER(1)         DEFAULT 1 NOT NULL,
    CREATED_AT            TIMESTAMP         NOT NULL,
    CREATED_BY            VARCHAR2(100)     NOT NULL,
    UPDATED_AT            TIMESTAMP,
    UPDATED_BY            VARCHAR2(100),
    CONSTRAINT GL_JOURNAL_HDR_PK PRIMARY KEY (ID_PK),
    CONSTRAINT UK_GL_JOURNAL_NO UNIQUE (JOURNAL_NO),
    CONSTRAINT CK_GL_JOURNAL_ACTIVE CHECK (ACTIVE_FL IN (0, 1))
);

CREATE INDEX IDX_GL_JOURNAL_HDR_DATE       ON GL_JOURNAL_HDR (JOURNAL_DATE);
CREATE INDEX IDX_GL_JOURNAL_HDR_TYPE_FK    ON GL_JOURNAL_HDR (JOURNAL_TYPE_ID_FK);
CREATE INDEX IDX_GL_JOURNAL_HDR_STATUS_FK  ON GL_JOURNAL_HDR (STATUS_ID_FK);
CREATE INDEX IDX_GL_JOURNAL_HDR_SRC_MOD    ON GL_JOURNAL_HDR (SOURCE_MODULE_ID_FK);
CREATE INDEX IDX_GL_JOURNAL_HDR_ACTIVE     ON GL_JOURNAL_HDR (ACTIVE_FL);
CREATE INDEX IDX_GL_JOURNAL_HDR_POST_FK    ON GL_JOURNAL_HDR (SOURCE_POSTING_ID_FK);

-- ── GL_JOURNAL_LINE ─────────────────────────────────────────
CREATE TABLE GL_JOURNAL_LINE (
    ID_PK                 NUMBER            NOT NULL,
    JOURNAL_ID_FK         NUMBER            NOT NULL,
    LINE_NO               NUMBER(5)         NOT NULL,
    ACCOUNT_ID_FK         NUMBER            NOT NULL,
    DEBIT_AMOUNT          NUMBER(18,2),
    CREDIT_AMOUNT         NUMBER(18,2),
    CUSTOMER_ID_FK        NUMBER,
    SUPPLIER_ID_FK        NUMBER,
    COST_CENTER_ID_FK     NUMBER,
    DESCRIPTION           VARCHAR2(500),
    CREATED_AT            TIMESTAMP         NOT NULL,
    CREATED_BY            VARCHAR2(100)     NOT NULL,
    UPDATED_AT            TIMESTAMP,
    UPDATED_BY            VARCHAR2(100),
    CONSTRAINT GL_JOURNAL_LINE_PK PRIMARY KEY (ID_PK),
    CONSTRAINT GL_JOURNAL_LINE_HDR_FK FOREIGN KEY (JOURNAL_ID_FK)
        REFERENCES GL_JOURNAL_HDR (ID_PK)
);

CREATE INDEX IDX_GL_JOURNAL_LINE_HDR_FK    ON GL_JOURNAL_LINE (JOURNAL_ID_FK);
CREATE INDEX IDX_GL_JOURNAL_LINE_ACCT_FK   ON GL_JOURNAL_LINE (ACCOUNT_ID_FK);
CREATE INDEX IDX_GL_JOURNAL_LINE_CUST_FK   ON GL_JOURNAL_LINE (CUSTOMER_ID_FK);
CREATE INDEX IDX_GL_JOURNAL_LINE_SUPP_FK   ON GL_JOURNAL_LINE (SUPPLIER_ID_FK);
CREATE INDEX IDX_GL_JOURNAL_LINE_CC_FK     ON GL_JOURNAL_LINE (COST_CENTER_ID_FK);

-- ── Seed Lookup Data ────────────────────────────────────────
-- Journal Types
INSERT INTO MD_MASTER_LOOKUP (ID_PK, LOOKUP_KEY, LOOKUP_NAME, LOOKUP_NAME_EN, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
SELECT MD_MASTER_LOOKUP_SEQ.NEXTVAL, 'GL_JOURNAL_TYPE', 'نوع القيد', 'Journal Type', 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM' FROM DUAL;

INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
SELECT MD_LOOKUP_DETAIL_SEQ.NEXTVAL, (SELECT ID_PK FROM MD_MASTER_LOOKUP WHERE LOOKUP_KEY='GL_JOURNAL_TYPE'), 'MANUAL', 'يدوي', 'Manual', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM' FROM DUAL;
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
SELECT MD_LOOKUP_DETAIL_SEQ.NEXTVAL, (SELECT ID_PK FROM MD_MASTER_LOOKUP WHERE LOOKUP_KEY='GL_JOURNAL_TYPE'), 'AUTOMATIC', 'آلي', 'Automatic', 2, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM' FROM DUAL;
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
SELECT MD_LOOKUP_DETAIL_SEQ.NEXTVAL, (SELECT ID_PK FROM MD_MASTER_LOOKUP WHERE LOOKUP_KEY='GL_JOURNAL_TYPE'), 'ADJUSTMENT', 'تسوية', 'Adjustment', 3, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM' FROM DUAL;
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
SELECT MD_LOOKUP_DETAIL_SEQ.NEXTVAL, (SELECT ID_PK FROM MD_MASTER_LOOKUP WHERE LOOKUP_KEY='GL_JOURNAL_TYPE'), 'REVERSAL', 'عكسي', 'Reversal', 4, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM' FROM DUAL;

-- Journal Status
INSERT INTO MD_MASTER_LOOKUP (ID_PK, LOOKUP_KEY, LOOKUP_NAME, LOOKUP_NAME_EN, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
SELECT MD_MASTER_LOOKUP_SEQ.NEXTVAL, 'GL_JOURNAL_STATUS', 'حالة القيد', 'Journal Status', 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM' FROM DUAL;

INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
SELECT MD_LOOKUP_DETAIL_SEQ.NEXTVAL, (SELECT ID_PK FROM MD_MASTER_LOOKUP WHERE LOOKUP_KEY='GL_JOURNAL_STATUS'), 'DRAFT', 'مسودة', 'Draft', 1, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM' FROM DUAL;
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
SELECT MD_LOOKUP_DETAIL_SEQ.NEXTVAL, (SELECT ID_PK FROM MD_MASTER_LOOKUP WHERE LOOKUP_KEY='GL_JOURNAL_STATUS'), 'APPROVED', 'معتمد', 'Approved', 2, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM' FROM DUAL;
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
SELECT MD_LOOKUP_DETAIL_SEQ.NEXTVAL, (SELECT ID_PK FROM MD_MASTER_LOOKUP WHERE LOOKUP_KEY='GL_JOURNAL_STATUS'), 'POSTED', 'مرحل', 'Posted', 3, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM' FROM DUAL;
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
SELECT MD_LOOKUP_DETAIL_SEQ.NEXTVAL, (SELECT ID_PK FROM MD_MASTER_LOOKUP WHERE LOOKUP_KEY='GL_JOURNAL_STATUS'), 'REVERSED', 'معكوس', 'Reversed', 4, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM' FROM DUAL;
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
SELECT MD_LOOKUP_DETAIL_SEQ.NEXTVAL, (SELECT ID_PK FROM MD_MASTER_LOOKUP WHERE LOOKUP_KEY='GL_JOURNAL_STATUS'), 'CANCELLED', 'ملغي', 'Cancelled', 5, 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM' FROM DUAL;

-- ── Seed SEC_PAGES ──────────────────────────────────────────

-- GL Journal Page (child of GL parent)
MERGE INTO SEC_PAGES tgt
USING (SELECT 'default' AS TENANT_ID, 'GL_JOURNAL' AS PAGE_CODE FROM DUAL) src
  ON (tgt.TENANT_ID = src.TENANT_ID AND tgt.PAGE_CODE = src.PAGE_CODE)
WHEN NOT MATCHED THEN INSERT
  (ID_PK, TENANT_ID, PAGE_CODE, NAME_AR, NAME_EN, ROUTE, ICON, MODULE, PARENT_ID_FK, DISPLAY_ORDER, IS_ACTIVE, DESCRIPTION, CREATED_AT, CREATED_BY)
  VALUES (SEC_PAGES_SEQ.NEXTVAL, 'default', 'GL_JOURNAL', N'القيود اليومية', 'Journal Entries', '/finance/gl/journals', 'ti ti-notebook', 'FINANCE',
          (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL' AND TENANT_ID = 'default'), 3, 1, 'GL Journal Entries management page', SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET
  tgt.NAME_AR = N'القيود اليومية', tgt.NAME_EN = 'Journal Entries',
  tgt.ROUTE = '/finance/gl/journals', tgt.ICON = 'ti ti-notebook', tgt.MODULE = 'FINANCE',
  tgt.PARENT_ID_FK = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL' AND TENANT_ID = 'default'),
  tgt.IS_ACTIVE = 1, tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';

-- ── Seed PERMISSIONS (CRUD) ─────────────────────────────────

MERGE INTO PERMISSIONS tgt
USING (SELECT 'PERM_GL_JOURNAL_VIEW' AS NAME FROM DUAL) src
  ON (tgt.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, TENANT_ID, PAGE_ID_FK, PERMISSION_TYPE, CREATED_AT, CREATED_BY)
  VALUES ('PERM_GL_JOURNAL_VIEW', 'default', (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_JOURNAL' AND TENANT_ID = 'default'), 'VIEW', SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET tgt.TENANT_ID = 'default', tgt.PAGE_ID_FK = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_JOURNAL' AND TENANT_ID = 'default'), tgt.PERMISSION_TYPE = 'VIEW', tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';

MERGE INTO PERMISSIONS tgt
USING (SELECT 'PERM_GL_JOURNAL_CREATE' AS NAME FROM DUAL) src
  ON (tgt.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, TENANT_ID, PAGE_ID_FK, PERMISSION_TYPE, CREATED_AT, CREATED_BY)
  VALUES ('PERM_GL_JOURNAL_CREATE', 'default', (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_JOURNAL' AND TENANT_ID = 'default'), 'CREATE', SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET tgt.TENANT_ID = 'default', tgt.PAGE_ID_FK = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_JOURNAL' AND TENANT_ID = 'default'), tgt.PERMISSION_TYPE = 'CREATE', tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';

MERGE INTO PERMISSIONS tgt
USING (SELECT 'PERM_GL_JOURNAL_UPDATE' AS NAME FROM DUAL) src
  ON (tgt.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, TENANT_ID, PAGE_ID_FK, PERMISSION_TYPE, CREATED_AT, CREATED_BY)
  VALUES ('PERM_GL_JOURNAL_UPDATE', 'default', (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_JOURNAL' AND TENANT_ID = 'default'), 'UPDATE', SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET tgt.TENANT_ID = 'default', tgt.PAGE_ID_FK = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_JOURNAL' AND TENANT_ID = 'default'), tgt.PERMISSION_TYPE = 'UPDATE', tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';

MERGE INTO PERMISSIONS tgt
USING (SELECT 'PERM_GL_JOURNAL_DELETE' AS NAME FROM DUAL) src
  ON (tgt.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, TENANT_ID, PAGE_ID_FK, PERMISSION_TYPE, CREATED_AT, CREATED_BY)
  VALUES ('PERM_GL_JOURNAL_DELETE', 'default', (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_JOURNAL' AND TENANT_ID = 'default'), 'DELETE', SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET tgt.TENANT_ID = 'default', tgt.PAGE_ID_FK = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_JOURNAL' AND TENANT_ID = 'default'), tgt.PERMISSION_TYPE = 'DELETE', tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';

-- ── Seed PERMISSIONS (Workflow Actions) ─────────────────────
-- These are page-linked but have no standard PERMISSION_TYPE (custom actions)

MERGE INTO PERMISSIONS tgt
USING (SELECT 'PERM_GL_JOURNAL_APPROVE' AS NAME FROM DUAL) src
  ON (tgt.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, TENANT_ID, PAGE_ID_FK, PERMISSION_TYPE, CREATED_AT, CREATED_BY)
  VALUES ('PERM_GL_JOURNAL_APPROVE', 'default', (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_JOURNAL' AND TENANT_ID = 'default'), NULL, SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET tgt.TENANT_ID = 'default', tgt.PAGE_ID_FK = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_JOURNAL' AND TENANT_ID = 'default'), tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';

MERGE INTO PERMISSIONS tgt
USING (SELECT 'PERM_GL_JOURNAL_POST' AS NAME FROM DUAL) src
  ON (tgt.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, TENANT_ID, PAGE_ID_FK, PERMISSION_TYPE, CREATED_AT, CREATED_BY)
  VALUES ('PERM_GL_JOURNAL_POST', 'default', (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_JOURNAL' AND TENANT_ID = 'default'), NULL, SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET tgt.TENANT_ID = 'default', tgt.PAGE_ID_FK = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_JOURNAL' AND TENANT_ID = 'default'), tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';

MERGE INTO PERMISSIONS tgt
USING (SELECT 'PERM_GL_JOURNAL_REVERSE' AS NAME FROM DUAL) src
  ON (tgt.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, TENANT_ID, PAGE_ID_FK, PERMISSION_TYPE, CREATED_AT, CREATED_BY)
  VALUES ('PERM_GL_JOURNAL_REVERSE', 'default', (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_JOURNAL' AND TENANT_ID = 'default'), NULL, SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET tgt.TENANT_ID = 'default', tgt.PAGE_ID_FK = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_JOURNAL' AND TENANT_ID = 'default'), tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';

MERGE INTO PERMISSIONS tgt
USING (SELECT 'PERM_GL_JOURNAL_CANCEL' AS NAME FROM DUAL) src
  ON (tgt.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, TENANT_ID, PAGE_ID_FK, PERMISSION_TYPE, CREATED_AT, CREATED_BY)
  VALUES ('PERM_GL_JOURNAL_CANCEL', 'default', (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_JOURNAL' AND TENANT_ID = 'default'), NULL, SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET tgt.TENANT_ID = 'default', tgt.PAGE_ID_FK = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_JOURNAL' AND TENANT_ID = 'default'), tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';
