-- ============================================================
-- V8: Posting Engine additions — REMAINING amount type + permission
-- ============================================================

-- ── 1. Add REMAINING to AMOUNT_SOURCE_TYPE lookup ───────────
INSERT INTO MD_LOOKUP_DETAIL (ID_PK, MASTER_LOOKUP_ID_FK, CODE, NAME_AR, NAME_EN, SORT_ORDER, IS_ACTIVE, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
SELECT MD_LOOKUP_DETAIL_SEQ.NEXTVAL,
       (SELECT ID_PK FROM MD_MASTER_LOOKUP WHERE LOOKUP_KEY = 'AMOUNT_SOURCE_TYPE'),
       'REMAINING', N'المتبقي', 'Remaining', 4, 1,
       SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM'
FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM MD_LOOKUP_DETAIL
    WHERE MASTER_LOOKUP_ID_FK = (SELECT ID_PK FROM MD_MASTER_LOOKUP WHERE LOOKUP_KEY = 'AMOUNT_SOURCE_TYPE')
      AND CODE = 'REMAINING'
);

-- ── 2. Add GL_POSTING_EXECUTE permission ────────────────────
MERGE INTO PERMISSIONS tgt
USING (SELECT 'PERM_GL_POSTING_EXECUTE' AS NAME FROM DUAL) src
  ON (tgt.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, TENANT_ID, PAGE_ID_FK, PERMISSION_TYPE, CREATED_AT, CREATED_BY)
  VALUES ('PERM_GL_POSTING_EXECUTE', 'default',
          (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_JOURNAL' AND TENANT_ID = 'default'),
          NULL, SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET
  tgt.TENANT_ID = 'default',
  tgt.PAGE_ID_FK = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_JOURNAL' AND TENANT_ID = 'default'),
  tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';
