-- ============================================================
-- V9: Posting Entity Support — sequences + permissions
-- ============================================================

-- ── 1. Create sequences for ACC_POSTING_MST / ACC_POSTING_DTL ─
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'ACC_POSTING_MST_SEQ';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE ACC_POSTING_MST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'ACC_POSTING_DTL_SEQ';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE ACC_POSTING_DTL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

-- ── 2. Add GL_POSTING_VIEW permission ───────────────────────
MERGE INTO PERMISSIONS tgt
USING (SELECT 'PERM_GL_POSTING_VIEW' AS NAME FROM DUAL) src
  ON (tgt.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, TENANT_ID, PAGE_ID_FK, PERMISSION_TYPE, CREATED_AT, CREATED_BY)
  VALUES ('PERM_GL_POSTING_VIEW', 'default',
          (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_JOURNAL' AND TENANT_ID = 'default'),
          NULL, SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET
  tgt.TENANT_ID = 'default',
  tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';

-- ── 3. Add GL_POSTING_GENERATE_JOURNAL permission ──────────
MERGE INTO PERMISSIONS tgt
USING (SELECT 'PERM_GL_POSTING_GENERATE_JOURNAL' AS NAME FROM DUAL) src
  ON (tgt.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, TENANT_ID, PAGE_ID_FK, PERMISSION_TYPE, CREATED_AT, CREATED_BY)
  VALUES ('PERM_GL_POSTING_GENERATE_JOURNAL', 'default',
          (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_JOURNAL' AND TENANT_ID = 'default'),
          NULL, SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET
  tgt.TENANT_ID = 'default',
  tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';
