-- ============================================================================
-- GL Module: SEC_PAGES + PERMISSIONS seed script  (IDEMPOTENT – safe to re-run)
-- Database: Oracle
-- Tenant:   'default'
-- Date:     2026-02-13  (v3 – fixes tenant mismatch + adds GL parent perms)
-- ============================================================================
-- IMPORTANT: Run the DIAGNOSTIC query first to see existing data:
--   SELECT NAME, TENANT_ID, PAGE_ID_FK FROM PERMISSIONS WHERE NAME LIKE 'PERM_GL%';
-- ============================================================================

-- ── 0. FIX: Force existing GL permissions to tenant 'default' ──────────────
-- These may exist with a wrong TENANT_ID from a prior seed. Fix them first.
UPDATE PERMISSIONS SET TENANT_ID = 'default', UPDATED_AT = SYSTIMESTAMP, UPDATED_BY = 'SYSTEM'
 WHERE NAME LIKE 'PERM_GL%' AND (TENANT_ID IS NULL OR TENANT_ID <> 'default');

-- ── 1. GL Parent Menu Page ─────────────────────────────────────────────────

MERGE INTO SEC_PAGES tgt
USING (SELECT 'default' AS TENANT_ID, 'GL' AS PAGE_CODE FROM DUAL) src
  ON (tgt.TENANT_ID = src.TENANT_ID AND tgt.PAGE_CODE = src.PAGE_CODE)
WHEN NOT MATCHED THEN INSERT
  (ID_PK, TENANT_ID, PAGE_CODE, NAME_AR, NAME_EN, ROUTE, ICON, MODULE, PARENT_ID_FK, DISPLAY_ORDER, IS_ACTIVE, DESCRIPTION, CREATED_AT, CREATED_BY)
  VALUES (SEC_PAGES_SEQ.NEXTVAL, 'default', 'GL', N'دفتر الأستاذ العام', 'General Ledger', '/finance/gl', 'ti ti-calculator', 'FINANCE', NULL, 1, 1, 'General Ledger parent menu', SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET
  tgt.NAME_AR = N'دفتر الأستاذ العام', tgt.NAME_EN = 'General Ledger',
  tgt.ROUTE = '/finance/gl', tgt.ICON = 'ti ti-calculator', tgt.MODULE = 'FINANCE',
  tgt.IS_ACTIVE = 1, tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';

-- ── 2. Chart of Accounts Page ──────────────────────────────────────────────

MERGE INTO SEC_PAGES tgt
USING (SELECT 'default' AS TENANT_ID, 'GL_ACCOUNT' AS PAGE_CODE FROM DUAL) src
  ON (tgt.TENANT_ID = src.TENANT_ID AND tgt.PAGE_CODE = src.PAGE_CODE)
WHEN NOT MATCHED THEN INSERT
  (ID_PK, TENANT_ID, PAGE_CODE, NAME_AR, NAME_EN, ROUTE, ICON, MODULE, PARENT_ID_FK, DISPLAY_ORDER, IS_ACTIVE, DESCRIPTION, CREATED_AT, CREATED_BY)
  VALUES (SEC_PAGES_SEQ.NEXTVAL, 'default', 'GL_ACCOUNT', N'دليل الحسابات', 'Chart of Accounts', '/finance/gl/accounts', 'ti ti-list-tree', 'FINANCE',
          (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL' AND TENANT_ID = 'default'), 1, 1, 'Chart of Accounts management page', SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET
  tgt.NAME_AR = N'دليل الحسابات', tgt.NAME_EN = 'Chart of Accounts',
  tgt.ROUTE = '/finance/gl/accounts', tgt.ICON = 'ti ti-list-tree', tgt.MODULE = 'FINANCE',
  tgt.PARENT_ID_FK = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL' AND TENANT_ID = 'default'),
  tgt.IS_ACTIVE = 1, tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';

-- ── 3. Accounting Rules Page ───────────────────────────────────────────────

MERGE INTO SEC_PAGES tgt
USING (SELECT 'default' AS TENANT_ID, 'GL_RULE' AS PAGE_CODE FROM DUAL) src
  ON (tgt.TENANT_ID = src.TENANT_ID AND tgt.PAGE_CODE = src.PAGE_CODE)
WHEN NOT MATCHED THEN INSERT
  (ID_PK, TENANT_ID, PAGE_CODE, NAME_AR, NAME_EN, ROUTE, ICON, MODULE, PARENT_ID_FK, DISPLAY_ORDER, IS_ACTIVE, DESCRIPTION, CREATED_AT, CREATED_BY)
  VALUES (SEC_PAGES_SEQ.NEXTVAL, 'default', 'GL_RULE', N'قواعد المحاسبة', 'Accounting Rules', '/finance/gl/rules', 'ti ti-scale', 'FINANCE',
          (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL' AND TENANT_ID = 'default'), 2, 1, 'Accounting Rules management page', SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET
  tgt.NAME_AR = N'قواعد المحاسبة', tgt.NAME_EN = 'Accounting Rules',
  tgt.ROUTE = '/finance/gl/rules', tgt.ICON = 'ti ti-scale', tgt.MODULE = 'FINANCE',
  tgt.PARENT_ID_FK = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL' AND TENANT_ID = 'default'),
  tgt.IS_ACTIVE = 1, tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';

-- ── 4. GL Parent Permissions (VIEW, CREATE, UPDATE, DELETE) ────────────────
-- These were MISSING in v2 – required for adding the GL parent page to a role.

MERGE INTO PERMISSIONS tgt
USING (SELECT 'PERM_GL_VIEW' AS NAME FROM DUAL) src
  ON (tgt.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, TENANT_ID, PAGE_ID_FK, PERMISSION_TYPE, CREATED_AT, CREATED_BY)
  VALUES ('PERM_GL_VIEW', 'default', (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL' AND TENANT_ID = 'default'), 'VIEW', SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET tgt.TENANT_ID = 'default', tgt.PAGE_ID_FK = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL' AND TENANT_ID = 'default'), tgt.PERMISSION_TYPE = 'VIEW', tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';

MERGE INTO PERMISSIONS tgt
USING (SELECT 'PERM_GL_CREATE' AS NAME FROM DUAL) src
  ON (tgt.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, TENANT_ID, PAGE_ID_FK, PERMISSION_TYPE, CREATED_AT, CREATED_BY)
  VALUES ('PERM_GL_CREATE', 'default', (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL' AND TENANT_ID = 'default'), 'CREATE', SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET tgt.TENANT_ID = 'default', tgt.PAGE_ID_FK = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL' AND TENANT_ID = 'default'), tgt.PERMISSION_TYPE = 'CREATE', tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';

MERGE INTO PERMISSIONS tgt
USING (SELECT 'PERM_GL_UPDATE' AS NAME FROM DUAL) src
  ON (tgt.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, TENANT_ID, PAGE_ID_FK, PERMISSION_TYPE, CREATED_AT, CREATED_BY)
  VALUES ('PERM_GL_UPDATE', 'default', (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL' AND TENANT_ID = 'default'), 'UPDATE', SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET tgt.TENANT_ID = 'default', tgt.PAGE_ID_FK = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL' AND TENANT_ID = 'default'), tgt.PERMISSION_TYPE = 'UPDATE', tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';

MERGE INTO PERMISSIONS tgt
USING (SELECT 'PERM_GL_DELETE' AS NAME FROM DUAL) src
  ON (tgt.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, TENANT_ID, PAGE_ID_FK, PERMISSION_TYPE, CREATED_AT, CREATED_BY)
  VALUES ('PERM_GL_DELETE', 'default', (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL' AND TENANT_ID = 'default'), 'DELETE', SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET tgt.TENANT_ID = 'default', tgt.PAGE_ID_FK = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL' AND TENANT_ID = 'default'), tgt.PERMISSION_TYPE = 'DELETE', tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';

-- ── 5. GL_ACCOUNT Permissions (VIEW, CREATE, UPDATE, DELETE) ───────────────
-- MERGE ON NAME only (ignores tenant) to catch existing rows with wrong TENANT_ID

MERGE INTO PERMISSIONS tgt
USING (SELECT 'PERM_GL_ACCOUNT_VIEW' AS NAME FROM DUAL) src
  ON (tgt.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, TENANT_ID, PAGE_ID_FK, PERMISSION_TYPE, CREATED_AT, CREATED_BY)
  VALUES ('PERM_GL_ACCOUNT_VIEW', 'default', (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_ACCOUNT' AND TENANT_ID = 'default'), 'VIEW', SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET tgt.TENANT_ID = 'default', tgt.PAGE_ID_FK = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_ACCOUNT' AND TENANT_ID = 'default'), tgt.PERMISSION_TYPE = 'VIEW', tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';

MERGE INTO PERMISSIONS tgt
USING (SELECT 'PERM_GL_ACCOUNT_CREATE' AS NAME FROM DUAL) src
  ON (tgt.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, TENANT_ID, PAGE_ID_FK, PERMISSION_TYPE, CREATED_AT, CREATED_BY)
  VALUES ('PERM_GL_ACCOUNT_CREATE', 'default', (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_ACCOUNT' AND TENANT_ID = 'default'), 'CREATE', SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET tgt.TENANT_ID = 'default', tgt.PAGE_ID_FK = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_ACCOUNT' AND TENANT_ID = 'default'), tgt.PERMISSION_TYPE = 'CREATE', tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';

MERGE INTO PERMISSIONS tgt
USING (SELECT 'PERM_GL_ACCOUNT_UPDATE' AS NAME FROM DUAL) src
  ON (tgt.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, TENANT_ID, PAGE_ID_FK, PERMISSION_TYPE, CREATED_AT, CREATED_BY)
  VALUES ('PERM_GL_ACCOUNT_UPDATE', 'default', (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_ACCOUNT' AND TENANT_ID = 'default'), 'UPDATE', SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET tgt.TENANT_ID = 'default', tgt.PAGE_ID_FK = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_ACCOUNT' AND TENANT_ID = 'default'), tgt.PERMISSION_TYPE = 'UPDATE', tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';

MERGE INTO PERMISSIONS tgt
USING (SELECT 'PERM_GL_ACCOUNT_DELETE' AS NAME FROM DUAL) src
  ON (tgt.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, TENANT_ID, PAGE_ID_FK, PERMISSION_TYPE, CREATED_AT, CREATED_BY)
  VALUES ('PERM_GL_ACCOUNT_DELETE', 'default', (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_ACCOUNT' AND TENANT_ID = 'default'), 'DELETE', SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET tgt.TENANT_ID = 'default', tgt.PAGE_ID_FK = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_ACCOUNT' AND TENANT_ID = 'default'), tgt.PERMISSION_TYPE = 'DELETE', tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';

-- ── 6. GL_RULE Permissions (VIEW, CREATE, UPDATE, DELETE) ──────────────────

MERGE INTO PERMISSIONS tgt
USING (SELECT 'PERM_GL_RULE_VIEW' AS NAME FROM DUAL) src
  ON (tgt.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, TENANT_ID, PAGE_ID_FK, PERMISSION_TYPE, CREATED_AT, CREATED_BY)
  VALUES ('PERM_GL_RULE_VIEW', 'default', (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_RULE' AND TENANT_ID = 'default'), 'VIEW', SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET tgt.TENANT_ID = 'default', tgt.PAGE_ID_FK = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_RULE' AND TENANT_ID = 'default'), tgt.PERMISSION_TYPE = 'VIEW', tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';

MERGE INTO PERMISSIONS tgt
USING (SELECT 'PERM_GL_RULE_CREATE' AS NAME FROM DUAL) src
  ON (tgt.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, TENANT_ID, PAGE_ID_FK, PERMISSION_TYPE, CREATED_AT, CREATED_BY)
  VALUES ('PERM_GL_RULE_CREATE', 'default', (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_RULE' AND TENANT_ID = 'default'), 'CREATE', SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET tgt.TENANT_ID = 'default', tgt.PAGE_ID_FK = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_RULE' AND TENANT_ID = 'default'), tgt.PERMISSION_TYPE = 'CREATE', tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';

MERGE INTO PERMISSIONS tgt
USING (SELECT 'PERM_GL_RULE_UPDATE' AS NAME FROM DUAL) src
  ON (tgt.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, TENANT_ID, PAGE_ID_FK, PERMISSION_TYPE, CREATED_AT, CREATED_BY)
  VALUES ('PERM_GL_RULE_UPDATE', 'default', (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_RULE' AND TENANT_ID = 'default'), 'UPDATE', SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET tgt.TENANT_ID = 'default', tgt.PAGE_ID_FK = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_RULE' AND TENANT_ID = 'default'), tgt.PERMISSION_TYPE = 'UPDATE', tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';

MERGE INTO PERMISSIONS tgt
USING (SELECT 'PERM_GL_RULE_DELETE' AS NAME FROM DUAL) src
  ON (tgt.NAME = src.NAME)
WHEN NOT MATCHED THEN INSERT (NAME, TENANT_ID, PAGE_ID_FK, PERMISSION_TYPE, CREATED_AT, CREATED_BY)
  VALUES ('PERM_GL_RULE_DELETE', 'default', (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_RULE' AND TENANT_ID = 'default'), 'DELETE', SYSTIMESTAMP, 'SYSTEM')
WHEN MATCHED THEN UPDATE SET tgt.TENANT_ID = 'default', tgt.PAGE_ID_FK = (SELECT ID_PK FROM SEC_PAGES WHERE PAGE_CODE = 'GL_RULE' AND TENANT_ID = 'default'), tgt.PERMISSION_TYPE = 'DELETE', tgt.UPDATED_AT = SYSTIMESTAMP, tgt.UPDATED_BY = 'SYSTEM';

-- ============================================================================
COMMIT;
