package com.example.erp.finance.gl.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.*;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AccountsChartCreateRequest {

    /**
     * Account name is required. Account number is auto-generated by the system.
     */
    @NotBlank(message = "{validation.required}")
    @Size(max = 500, message = "{validation.size}")
    private String accountChartName;

    @NotBlank(message = "{validation.required}")
    @Size(max = 50, message = "{validation.size}")
    private String accountType;

    /**
     * Parent account PK (ACCOUNT_CHART_FK). Null for root accounts.
     */
    private Long accountChartFk;

    @NotNull(message = "{validation.required}")
    private Long organizationFk;

    private Long organizationSubFk;

    @Builder.Default
    private Boolean isActive = Boolean.TRUE;
}
